import { describe, expect, it } from 'vitest';
import { miniCity } from '../levels/mini-city';
import { testCity } from '../levels/test-city';
import { createLine, createStop, makeLine, TransitNetwork } from '../transit';
import { World } from '../world';
import { AutosaveController, GameSession, MemorySaveRepository } from './index';

const player = { id: 'local-player', displayName: 'Planner', achievementIds: [], settings: { autosave: true } };
const busNetwork = (): TransitNetwork => { let network = new TransitNetwork(); network = createStop(network, { id: 'a', name: 'A', coordinate: { latitude: 41.88, longitude: -87.63 }, kind: 'stop', supportedModes: ['BUS'] }); network = createStop(network, { id: 'b', name: 'B', coordinate: { latitude: 41.88, longitude: -87.629 }, kind: 'stop', supportedModes: ['BUS'] }); return createLine(network, makeLine('bus', 'Bus', 'BUS', ['a', 'b'], network)); };
describe('Game session integration', () => {
  it('runs a bus startup through commands, simulation, finance, and score', () => { const session = new GameSession(new World(testCity), 7, player); session.replaceNetwork(busNetwork()); session.advanceBy(9 * 3600 + 30 * 60); const dashboard = session.dashboard(); expect(dashboard.simulation.operations?.vehicles.length).toBeGreaterThan(0); expect(dashboard.simulation.finances.allTime.operatingCostCents).toBeGreaterThan(0); expect(dashboard.achievements.map((item) => item.id)).toContain('first-route'); expect(dashboard.score.total).toBeGreaterThanOrEqual(0); });
  it('keeps unaffordable construction atomic and supports versioned save/load', async () => { const session = new GameSession(new World(testCity), 7, player); const failed = session.execute({ type: 'BUILD', proposal: { kind: 'station', id: 'too-expensive', mode: 'SUBWAY', elevationMeters: -5000, footprint: { center: { latitude: 41.87, longitude: -87.64 }, widthMeters: 300, lengthMeters: 300 } } }); expect(failed.ok).toBe(false); const save = session.save(); const repository = new MemorySaveRepository(); await repository.save(save); const restored = new GameSession(new World(testCity), 7, player, await repository.load('test-city') ?? undefined); expect(restored.save().economy).toEqual(save.economy); expect(restored.importDesign({ ...session.exportDesign(), levelId: 'mini-city' }).ok).toBe(false); });
  it('loads a second static city through the same session interface without state leakage', () => { const first = new GameSession(new World(testCity), 7, player); first.replaceNetwork(busNetwork()); const second = new GameSession(new World(miniCity), 7, player); expect(first.dashboard().lineCounts.BUS).toBe(1); expect(second.dashboard().lineCounts.BUS).toBe(0); expect(second.save().levelId).toBe('mini-city'); });
  it('autosaves on a bounded simulated-time cadence', async () => { const repository = new MemorySaveRepository(); const session = new GameSession(new World(testCity), 7, player); const autosave = new AutosaveController(repository, 60); expect(await autosave.saveIfDue(session)).toBe(true); expect(await autosave.saveIfDue(session)).toBe(false); session.advanceBy(60); expect(await autosave.saveIfDue(session)).toBe(true); });
});
