import type { Bounds, Coordinate } from '../world';

const EARTH_RADIUS_METERS = 6_371_000;
const radians = (degrees: number): number => degrees * Math.PI / 180;
const project = (coordinate: Coordinate, latitudeReference: number): { x: number; y: number } => ({ x: radians(coordinate.longitude) * EARTH_RADIUS_METERS * Math.cos(radians(latitudeReference)), y: radians(coordinate.latitude) * EARTH_RADIUS_METERS });

/** All public distances and offsets use meters. Coordinates remain WGS84 latitude/longitude. */
export function distanceMeters(a: Coordinate, b: Coordinate): number { const dLat = radians(b.latitude - a.latitude); const dLon = radians(b.longitude - a.longitude); const sinLat = Math.sin(dLat / 2); const sinLon = Math.sin(dLon / 2); const h = sinLat * sinLat + Math.cos(radians(a.latitude)) * Math.cos(radians(b.latitude)) * sinLon * sinLon; return 2 * EARTH_RADIUS_METERS * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h)); }
export function interpolateSegment(a: Coordinate, b: Coordinate, fraction: number): Coordinate { const t = Math.max(0, Math.min(1, fraction)); return { latitude: a.latitude + (b.latitude - a.latitude) * t, longitude: a.longitude + (b.longitude - a.longitude) * t }; }
export function interpolatePolyline(line: readonly Coordinate[], distance: number): Coordinate { if (line.length === 0) throw new Error('Cannot interpolate an empty polyline'); if (line.length === 1) return line[0]; let remaining = Math.max(0, distance); for (let index = 0; index < line.length - 1; index += 1) { const segmentLength = distanceMeters(line[index], line[index + 1]); if (remaining <= segmentLength || index === line.length - 2) return interpolateSegment(line[index], line[index + 1], segmentLength === 0 ? 0 : remaining / segmentLength); remaining -= segmentLength; } return line[line.length - 1]; }
export interface NearestPoint { readonly coordinate: Coordinate; readonly distanceMeters: number; readonly segmentIndex: number; readonly fraction: number; }
export function nearestPointOnSegment(point: Coordinate, start: Coordinate, end: Coordinate): NearestPoint { const reference = (point.latitude + start.latitude + end.latitude) / 3; const p = project(point, reference); const a = project(start, reference); const b = project(end, reference); const dx = b.x - a.x; const dy = b.y - a.y; const t = dx === 0 && dy === 0 ? 0 : Math.max(0, Math.min(1, ((p.x - a.x) * dx + (p.y - a.y) * dy) / (dx * dx + dy * dy))); const coordinate = interpolateSegment(start, end, t); return { coordinate, distanceMeters: distanceMeters(point, coordinate), segmentIndex: 0, fraction: t }; }
export function nearestPointOnPolyline(point: Coordinate, line: readonly Coordinate[]): NearestPoint { if (line.length < 2) throw new Error('A polyline must have at least two points'); return line.slice(0, -1).map((start, segmentIndex) => ({ ...nearestPointOnSegment(point, start, line[segmentIndex + 1]), segmentIndex })).reduce((nearest, candidate) => candidate.distanceMeters < nearest.distanceMeters ? candidate : nearest); }
export function boundsForCoordinates(coordinates: readonly Coordinate[]): Bounds { if (coordinates.length === 0) throw new Error('Cannot determine bounds for no coordinates'); return coordinates.reduce<Bounds>((bounds, coordinate) => ({ southWest: { latitude: Math.min(bounds.southWest.latitude, coordinate.latitude), longitude: Math.min(bounds.southWest.longitude, coordinate.longitude) }, northEast: { latitude: Math.max(bounds.northEast.latitude, coordinate.latitude), longitude: Math.max(bounds.northEast.longitude, coordinate.longitude) } }), { southWest: coordinates[0], northEast: coordinates[0] }); }
export function pointInPolygon(point: Coordinate, polygon: readonly Coordinate[]): boolean { let inside = false; for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i, i += 1) { const a = polygon[i]; const b = polygon[j]; const intersects = ((a.latitude > point.latitude) !== (b.latitude > point.latitude)) && point.longitude < (b.longitude - a.longitude) * (point.latitude - a.latitude) / (b.latitude - a.latitude) + a.longitude; if (intersects) inside = !inside; } return inside; }
const orientation = (a: Coordinate, b: Coordinate, c: Coordinate): number => (b.longitude - a.longitude) * (c.latitude - a.latitude) - (b.latitude - a.latitude) * (c.longitude - a.longitude);
function onSegment(a: Coordinate, b: Coordinate, point: Coordinate): boolean { return point.longitude >= Math.min(a.longitude, b.longitude) && point.longitude <= Math.max(a.longitude, b.longitude) && point.latitude >= Math.min(a.latitude, b.latitude) && point.latitude <= Math.max(a.latitude, b.latitude); }
export function segmentsIntersect(a: Coordinate, b: Coordinate, c: Coordinate, d: Coordinate): boolean { const abC = orientation(a, b, c); const abD = orientation(a, b, d); const cdA = orientation(c, d, a); const cdB = orientation(c, d, b); if (((abC > 0 && abD < 0) || (abC < 0 && abD > 0)) && ((cdA > 0 && cdB < 0) || (cdA < 0 && cdB > 0))) return true; const epsilon = 1e-12; return (Math.abs(abC) < epsilon && onSegment(a, b, c)) || (Math.abs(abD) < epsilon && onSegment(a, b, d)) || (Math.abs(cdA) < epsilon && onSegment(c, d, a)) || (Math.abs(cdB) < epsilon && onSegment(c, d, b)); }
