import { useCallback, useEffect, useRef, useState, type MouseEvent as ReactMouseEvent } from 'react';
import type { World } from '../world';
import { MapLibreController } from './MapLibreController';
import { buildingEmployment, buildingPopulation } from './queries';
import type { MapController, MapLayerVisibility, MapSelection, TransitOverlay } from './types';
import { PopulationDebug } from '../population/PopulationDebug';
import { TransitNetworkDebug } from '../transit/TransitNetworkDebug';
import { ConstructionDebug } from '../construction/ConstructionDebug';
import { ModeReference } from '../modes';
import { OperationsDebug } from '../operations/OperationsDebug';
import { TransitNetwork } from '../transit';
import { Economy, FinancePanel } from '../economy';

const initialVisibility: MapLayerVisibility = { population: 'points', workplaces: true, pois: true, water: true, roadIds: false, buildingIds: false, bounds: false };
const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
export function MapView({ world, onBack }: { readonly world: World; readonly onBack: () => void }) {
  const container = useRef<HTMLDivElement>(null); const controller = useRef<MapController | null>(null); const [selection, setSelection] = useState<MapSelection>(null); const [coordinate, setCoordinate] = useState<{ readonly latitude: number; readonly longitude: number } | null>(null); const [visibility, setVisibility] = useState(initialVisibility); const [transitOverlay, setTransitOverlay] = useState<TransitOverlay>({ lines: [], stops: [] }); const [network, setNetwork] = useState(() => new TransitNetwork()); const [economy] = useState(() => new Economy(world.definition.economy.startingBudget)); const [, setEconomyVersion] = useState(0);
  useEffect(() => { if (!container.current) return undefined; const instance = new MapLibreController({ container: container.current, world, onSelection: setSelection, onCoordinate: setCoordinate }); controller.current = instance; return () => { instance.destroy(); controller.current = null; }; }, [world]);
  useEffect(() => { controller.current?.setTransitOverlay(transitOverlay); }, [transitOverlay]);
  const setToggle = (key: keyof Omit<MapLayerVisibility, 'population'>, value: boolean): void => { controller.current?.setLayerVisibility(key, value); setVisibility((current) => ({ ...current, [key]: value })); };
  const updateVehicles = useCallback((snapshot: import('../operations').OperationsSnapshot): void => setTransitOverlay((current) => ({ ...current, vehicles: snapshot.vehicles.map((vehicle) => ({ id: vehicle.id, coordinate: vehicle.coordinate })) })), []); const refreshEconomy = useCallback(() => setEconomyVersion((value) => value + 1), []);
  const setPopulation = (value: MapLayerVisibility['population']): void => { controller.current?.setPopulationMode(value); setVisibility((current) => ({ ...current, population: value })); };
  const captureMapCoordinate = (event: ReactMouseEvent<HTMLElement>): void => { const bounds = event.currentTarget.getBoundingClientRect(); const mapCoordinate = controller.current?.coordinateFromScreen(event.clientX - bounds.left, event.clientY - bounds.top); if (mapCoordinate) setCoordinate(mapCoordinate); };
  return <main className="map-page"><header className="map-header"><button className="back" type="button" onClick={onBack}>← All levels</button><div><p className="eyebrow">MAP & GEOGRAPHIC ENGINE</p><h1>{world.definition.metadata.name}</h1></div><button type="button" onClick={() => controller.current?.resetCamera()}>Reset camera</button></header><div className="map-layout"><section className="map-canvas" aria-label="Interactive city map" onClick={captureMapCoordinate}><div ref={container} className="maplibre-container" /><aside className="map-legend" aria-label="Map legend"><strong>Legend</strong><span><i className="legend-line local" />Local roads</span><span><i className="legend-line arterial" />Arterial roads</span><span><i className="legend-line highway" />Highways</span><span><i className="legend-dot residents" />Residents</span><span><i className="legend-dot jobs" />Jobs</span><span><i className="legend-dot poi" />POIs & landmarks</span><span><i className="legend-line water" />Water</span></aside></section><aside className="map-sidebar"><FinancePanel economy={economy} timestampSeconds={0} onChange={refreshEconomy} /><section><p className="eyebrow">LAYERS</p><h2>City view</h2><fieldset><legend className="sr-only">Population display</legend>{(['hidden', 'points', 'density'] as const).map((mode) => <label key={mode}><input type="radio" name="population" checked={visibility.population === mode} onChange={() => setPopulation(mode)} /> Population: {mode}</label>)}</fieldset>{(['workplaces', 'pois', 'water', 'roadIds', 'buildingIds', 'bounds'] as const).map((key) => <label key={key}><input type="checkbox" checked={visibility[key]} onChange={(event) => setToggle(key, event.target.checked)} /> {({ workplaces: 'Jobs', pois: 'POIs & landmarks', water: 'Water', roadIds: 'Road IDs', buildingIds: 'Building IDs', bounds: 'Level bounds' } as Record<string, string>)[key]}</label>)}</section><InspectionPanel world={world} selection={selection} coordinate={coordinate} /><ModeReference /><PopulationDebug world={world} /><TransitNetworkDebug coordinate={coordinate} onOverlay={setTransitOverlay} onNetwork={setNetwork} /><OperationsDebug network={network} onSnapshot={updateVehicles} onEvents={(events) => { economy.consumeOperationsEvents(events); refreshEconomy(); }} /><ConstructionDebug world={world} coordinate={coordinate} economy={economy} onEconomyChange={refreshEconomy} /></aside></div></main>;
}
function InspectionPanel({ world, selection, coordinate }: { readonly world: World; readonly selection: MapSelection; readonly coordinate: { readonly latitude: number; readonly longitude: number } | null }) {
  let content: React.ReactNode = <p>Click a road, building, workplace, or point of interest to inspect it.</p>;
  if (selection?.kind === 'road') { const item = world.roadsById.get(selection.id); content = item && <dl><dt>ID</dt><dd>{item.id}</dd><dt>Name</dt><dd>{item.name ?? 'Unnamed'}</dd><dt>Class</dt><dd>{item.classification}</dd><dt>Assumed speed</dt><dd>{item.speedKph ? `${item.speedKph} km/h` : 'Not specified'}</dd></dl>; }
  if (selection?.kind === 'building') { const item = world.buildingsById.get(selection.id); content = item && <dl><dt>ID</dt><dd>{item.id}</dd><dt>Category</dt><dd>{item.category ?? 'Not specified'}</dd><dt>Acquisition value</dt><dd>{currency.format(item.acquisitionValue)}</dd><dt>Residents</dt><dd>{buildingPopulation(world, item.id).toLocaleString()}</dd><dt>Employment</dt><dd>{buildingEmployment(world, item.id).toLocaleString()}</dd></dl>; }
  if (selection?.kind === 'workplace') { const item = world.workplacesById.get(selection.id); content = item && <dl><dt>ID</dt><dd>{item.id}</dd><dt>Name</dt><dd>{item.displayName ?? 'Unnamed'}</dd><dt>Jobs</dt><dd>{item.jobs.toLocaleString()}</dd><dt>Building</dt><dd>{item.buildingId ?? 'None'}</dd></dl>; }
  if (selection?.kind === 'poi') { const item = world.pointsOfInterestById.get(selection.id); content = item ? <dl><dt>ID</dt><dd>{item.id}</dd><dt>Name</dt><dd>{item.displayName ?? 'Unnamed'}</dd><dt>Category</dt><dd>{item.category}</dd></dl> : <p>Landmark selected: {selection.id}</p>; }
  return <section className="inspection"><p className="eyebrow">INSPECTOR</p><h2>{selection?.kind ? selection.kind : 'No selection'}</h2>{content}{coordinate && <p className="coordinate">Last map coordinate: {coordinate.latitude.toFixed(5)}, {coordinate.longitude.toFixed(5)}</p>}</section>;
}
