import type { World } from '../world';
import { SeededRandom } from './random';
import { ResidentState, type PopulationGenerationOptions, type Resident } from './types';

const DEFAULTS = { targetAgentCount: 360, employmentRate: .78, activityRate: .12 };
export function generateResidents(world: World, options: PopulationGenerationOptions): readonly Resident[] {
  const config = { ...DEFAULTS, ...options }; if (config.targetAgentCount < 1 || config.employmentRate < 0 || config.employmentRate > 1 || config.activityRate < 0 || config.activityRate > 1) throw new Error('Invalid population generation options');
  const records = world.definition.population; if (records.some((record) => !Number.isFinite(record.residents) || record.residents < 0)) throw new Error('Population records must have nonnegative weights'); const totalPopulation = records.reduce((total, record) => total + record.residents, 0); if (totalPopulation <= 0) throw new Error('Level must have positive population to generate residents'); if (world.definition.workplaces.length === 0) throw new Error('Level must contain workplaces to generate residents');
  const random = new SeededRandom(config.seed); const weightedHomes = records.flatMap((record) => Array.from({ length: Math.max(0, Math.round(record.residents / totalPopulation * config.targetAgentCount)) }, () => record));
  while (weightedHomes.length < config.targetAgentCount) weightedHomes.push(random.pick(records));
  const homes = random.shuffle(weightedHomes).slice(0, config.targetAgentCount); const workerCount = Math.round(config.targetAgentCount * config.employmentRate); const workplaceSlots = world.definition.workplaces.flatMap((workplace) => Array.from({ length: Math.max(1, Math.round(workplace.jobs / world.definition.workplaces.reduce((total, item) => total + item.jobs, 0) * workerCount)) }, () => workplace));
  while (workplaceSlots.length < workerCount) workplaceSlots.push(random.pick(world.definition.workplaces)); const assignments = random.shuffle(workplaceSlots).slice(0, workerCount); const pois = world.definition.pointsOfInterest;
  return homes.map((homeRecord, index) => { const workplace = index < workerCount ? assignments[index] : undefined; const activity = !workplace && pois.length > 0 && random.next() < config.activityRate ? random.pick(pois) : undefined; const dailyPurpose = workplace ? 'work' : 'activity'; const outboundDepartureMinute = Math.max(0, 8 * 60 + random.integer(-75, 75)); const returnDepartureMinute = Math.max(outboundDepartureMinute + 60, 17 * 60 + random.integer(-90, 90)); return { id: `resident-${String(index + 1).padStart(4, '0')}`, simulationWeight: totalPopulation / config.targetAgentCount, home: homeRecord.coordinate, homePopulationRecordId: homeRecord.id, workplaceId: workplace?.id, workplaceCoordinate: workplace?.coordinate, activityPoiId: activity?.id, activityCoordinate: activity?.coordinate, outboundDepartureMinute, returnDepartureMinute, dailyPurpose, state: ResidentState.AtHome }; });
}
