import { useMemo, useState } from 'react';
import type { World } from '../world';
import { PopulationSimulation } from './PopulationSimulation';

const clock = (minutes: number): string => `${String(Math.floor((minutes % 1440) / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`;
export function PopulationDebug({ world }: { readonly world: World }) {
  const [seedText, setSeedText] = useState('12345'); const [generation, setGeneration] = useState(0); const [, setRevision] = useState(0); const simulation = useMemo(() => new PopulationSimulation(world, { seed: Number(seedText) || 12345 }), [world, seedText, generation]); const summary = simulation.summary();
  const advance = (minutes: number): void => { simulation.tick({ absoluteMinutes: summary.absoluteMinutes + minutes }); setRevision((value) => value + 1); };
  const goToTime = (minuteOfDay: number): void => { const current = summary.absoluteMinutes; let target = Math.floor(current / 1440) * 1440 + minuteOfDay; if (target <= current) target += 1440; advance(target - current); };
  return <section className="population-debug"><p className="eyebrow">POPULATION DEBUG</p><h2>Demand harness</h2><label>Seed <input aria-label="Population simulation seed" value={seedText} inputMode="numeric" onChange={(event) => setSeedText(event.target.value)} /></label><button type="button" onClick={() => setGeneration((value) => value + 1)}>Regenerate residents</button><div className="time-buttons"><button type="button" onClick={() => advance(30)}>Advance 30m</button><button type="button" onClick={() => goToTime(9 * 60 + 30)}>Morning 09:30</button><button type="button" onClick={() => goToTime(19 * 60)}>Evening 19:00</button></div><button type="button" onClick={() => { simulation.resolveAllWithAlternativeMode(); setRevision((value) => value + 1); }}>Resolve requests with fallback</button><dl><dt>Time</dt><dd>{clock(summary.absoluteMinutes)}</dd><dt>Residents</dt><dd>{simulation.getResidents().length}</dd><dt>At home</dt><dd>{summary.atHome}</dd><dt>Route requests</dt><dd>{summary.activeRequests}</dd><dt>At destination</dt><dd>{summary.atDestination}</dd><dt>Return pending</dt><dd>{summary.returnTripsPending}</dd></dl><p className="debug-note">Requests represent intent only. “Fallback” records an assumed alternative mode; no transit trip is simulated.</p><h3>Resident samples</h3><ul>{simulation.getResidents().slice(0, 3).map((resident) => <li key={resident.id}><strong>{resident.id}</strong><br />{resident.homePopulationRecordId} → {resident.workplaceId ?? resident.activityPoiId ?? 'No destination'} · depart {clock(resident.outboundDepartureMinute)} · {resident.state}</li>)}</ul><h3>Unresolved requests</h3><ul>{simulation.getTravelRequests().filter((request) => request.status === 'unresolved').slice(0, 3).map((request) => <li key={request.id}><strong>{request.residentId}</strong><br />{request.purpose} at {clock(request.desiredDepartureMinute)}</li>)}</ul></section>;
}
