import { distanceMeters } from '../map/geometry';
import { TransitNetwork } from './TransitNetwork';
import type { TransitInfrastructureValidator, TransitLine, TransitMode, TransitSegment, TransitStop } from './types';

const assertId = (id: string, kind: string): void => { if (!id.trim()) throw new Error(`${kind} requires a non-empty ID`); };
const unique = (items: readonly string[]): boolean => new Set(items).size === items.length;
const validate = (validator: TransitInfrastructureValidator | undefined, proposal: Parameters<TransitInfrastructureValidator['validateProposal']>[0]): void => { const result = validator?.validateProposal(proposal); if (result && !result.valid) throw new Error(`Infrastructure proposal rejected: ${result.reasons.join(', ')}`); };
export function createStop(network: TransitNetwork, stop: TransitStop, validator?: TransitInfrastructureValidator): TransitNetwork { assertId(stop.id, 'Stop'); if (network.getStop(stop.id)) throw new Error(`Duplicate stop ID "${stop.id}"`); if (stop.supportedModes.length === 0) throw new Error(`Stop "${stop.id}" must support a transit mode`); validate(validator, { kind: 'stop', coordinate: stop.coordinate, modes: stop.supportedModes }); return network.withDefinition({ ...network.definition, stops: [...network.definition.stops, stop] }); }
export function deleteStop(network: TransitNetwork, stopId: string): TransitNetwork { if (!network.getStop(stopId)) throw new Error(`Unknown stop "${stopId}"`); const affected = network.definition.lines.filter((line) => line.stopIds.includes(stopId)); if (affected.length > 0) throw new Error(`Cannot delete stop "${stopId}" while it is served by a line`); return network.withDefinition({ ...network.definition, stops: network.definition.stops.filter((stop) => stop.id !== stopId), transferComplexes: network.definition.transferComplexes.map((complex) => ({ ...complex, stopIds: complex.stopIds.filter((id) => id !== stopId) })).filter((complex) => complex.stopIds.length > 0) }); }
export function createLine(network: TransitNetwork, line: TransitLine, validator?: TransitInfrastructureValidator): TransitNetwork { assertId(line.id, 'Line'); if (network.getLine(line.id)) throw new Error(`Duplicate line ID "${line.id}"`); validateLine(network, line); validate(validator, { kind: 'line', mode: line.mode, stopIds: line.stopIds }); return network.withDefinition({ ...network.definition, lines: [...network.definition.lines, line] }); }
function validateLine(network: TransitNetwork, line: TransitLine): void { if (!line.name.trim()) throw new Error(`Line "${line.id}" requires a name`); if (line.stopIds.length < 2) throw new Error(`Line "${line.id}" requires at least two stops`); if (!unique(line.stopIds)) throw new Error(`Line "${line.id}" cannot contain duplicate stops`); for (const id of line.stopIds) { const stop = network.getStop(id); if (!stop) throw new Error(`Line "${line.id}" references unknown stop "${id}"`); if (!stop.supportedModes.includes(line.mode)) throw new Error(`Stop "${id}" is not compatible with ${line.mode}`); } if (line.segments.length !== line.stopIds.length - 1) throw new Error(`Line "${line.id}" must have one segment between each adjacent stop`); line.segments.forEach((segment, index) => { if (segment.startStopId !== line.stopIds[index] || segment.endStopId !== line.stopIds[index + 1] || segment.geometry.length < 2) throw new Error(`Line "${line.id}" has invalid segment "${segment.id}"`); }); }
export function addStopToLine(network: TransitNetwork, lineId: string, stopId: string, position?: number): TransitNetwork { const line = network.getLine(lineId); const stop = network.getStop(stopId); if (!line || !stop) throw new Error('Line and stop must exist'); if (line.stopIds.includes(stopId)) throw new Error(`Line "${lineId}" already contains stop "${stopId}"`); if (!stop.supportedModes.includes(line.mode)) throw new Error(`Stop "${stopId}" is not compatible with ${line.mode}`); const index = position ?? line.stopIds.length; const stopIds = [...line.stopIds.slice(0, index), stopId, ...line.stopIds.slice(index)]; return replaceLine(network, rebuildLine(line, stopIds, network)); }
export function removeStopFromLine(network: TransitNetwork, lineId: string, stopId: string): TransitNetwork { const line = network.getLine(lineId); if (!line) throw new Error(`Unknown line "${lineId}"`); const stopIds = line.stopIds.filter((id) => id !== stopId); if (stopIds.length < 2) throw new Error('A line must retain at least two stops'); return replaceLine(network, rebuildLine(line, stopIds, network)); }
export function reorderLineStops(network: TransitNetwork, lineId: string, stopIds: readonly string[]): TransitNetwork { const line = network.getLine(lineId); if (!line) throw new Error(`Unknown line "${lineId}"`); if (stopIds.length !== line.stopIds.length || !unique(stopIds) || stopIds.some((id) => !line.stopIds.includes(id))) throw new Error('Reordered stops must be the line’s unique existing stops'); return replaceLine(network, rebuildLine(line, stopIds, network)); }
export function renameLine(network: TransitNetwork, lineId: string, name: string): TransitNetwork { const line = network.getLine(lineId); if (!line || !name.trim()) throw new Error('Line and non-empty name are required'); return replaceLine(network, { ...line, name }); }
export function setLineActive(network: TransitNetwork, lineId: string, active: boolean): TransitNetwork { const line = network.getLine(lineId); if (!line) throw new Error(`Unknown line "${lineId}"`); return replaceLine(network, { ...line, active }); }
export function setLineAlignment(network: TransitNetwork, lineId: string, segments: readonly TransitSegment[]): TransitNetwork { const line = network.getLine(lineId); if (!line) throw new Error(`Unknown line "${lineId}"`); const replacement = { ...line, segments }; validateLine(network, replacement); return replaceLine(network, replacement); }
export function deleteLine(network: TransitNetwork, lineId: string): TransitNetwork { if (!network.getLine(lineId)) throw new Error(`Unknown line "${lineId}"`); return network.withDefinition({ ...network.definition, lines: network.definition.lines.filter((line) => line.id !== lineId) }); }
export function createTransferComplex(network: TransitNetwork, id: string, name: string, stopIds: readonly string[]): TransitNetwork { assertId(id, 'Transfer complex'); if (!name.trim() || stopIds.length < 2 || !unique(stopIds) || stopIds.some((stopId) => !network.getStop(stopId))) throw new Error('Transfer complex requires two unique existing stops'); if (network.getTransferComplex(id)) throw new Error(`Duplicate transfer complex ID "${id}"`); return network.withDefinition({ ...network.definition, transferComplexes: [...network.definition.transferComplexes, { id, name, stopIds }], stops: network.definition.stops.map((stop) => stopIds.includes(stop.id) ? { ...stop, parentComplexId: id } : stop) }); }
export function makeLine(id: string, name: string, mode: TransitMode, stopIds: readonly string[], network: TransitNetwork): TransitLine { const segments = stopIds.slice(0, -1).map((startStopId, index) => { const endStopId = stopIds[index + 1]; const start = network.getStop(startStopId); const end = network.getStop(endStopId); if (!start || !end) throw new Error('Cannot create alignment for unknown stop'); return { id: `${id}-segment-${index + 1}`, startStopId, endStopId, geometry: [start.coordinate, end.coordinate], engineering: { reservedRightOfWay: false } }; }); return { id, name, mode, stopIds, segments, direction: 'bidirectional', active: true, serviceSettings: { plannedHeadwayMinutes: 12 } }; }
function rebuildLine(line: TransitLine, stopIds: readonly string[], network: TransitNetwork): TransitLine { return makeLine(line.id, line.name, line.mode, stopIds, network); }
function replaceLine(network: TransitNetwork, replacement: TransitLine): TransitNetwork { return network.withDefinition({ ...network.definition, lines: network.definition.lines.map((line) => line.id === replacement.id ? replacement : line) }); }
export const distanceBetweenStops = (a: TransitStop, b: TransitStop): number => distanceMeters(a.coordinate, b.coordinate);
