import { useEffect, useRef, useState } from 'react';
import type { Coordinate } from '../world';
import type { TransitOverlay } from '../map';
import { createLine, createStop, createTransferComplex, deleteLine, makeLine, renameLine, TransitGraph, TransitNetwork, type TransitMode } from './index';

const colors: Record<TransitMode, string> = { BUS: '#3d78ad', TRAM: '#2d936c', SUBWAY: '#a14eaa' };
const toOverlay = (network: TransitNetwork): TransitOverlay => ({ lines: network.definition.lines.filter((line) => line.active).flatMap((line) => line.segments.map((segment) => ({ id: segment.id, geometry: segment.geometry, color: colors[line.mode] }))), stops: network.definition.stops.map((stop) => ({ id: stop.id, coordinate: stop.coordinate, name: stop.name })) });
export function TransitNetworkDebug({ coordinate, onOverlay }: { readonly coordinate: Coordinate | null; readonly onOverlay: (overlay: TransitOverlay) => void }) {
  const [network, setNetwork] = useState(() => new TransitNetwork()); const [mode, setMode] = useState<TransitMode>('BUS'); const [placementEnabled, setPlacementEnabled] = useState(false); const [selectedStops, setSelectedStops] = useState<readonly string[]>([]); const [selectedLineId, setSelectedLineId] = useState(''); const [lineName, setLineName] = useState('New line'); const [message, setMessage] = useState('Click the map to place stops when placement is enabled.'); const lastPlaced = useRef<string | null>(null);
  useEffect(() => { onOverlay(toOverlay(network)); }, [network, onOverlay]);
  useEffect(() => { if (!placementEnabled || !coordinate) return; const key = `${coordinate.latitude},${coordinate.longitude}`; if (key === lastPlaced.current) return; lastPlaced.current = key; try { const id = `stop-${network.definition.stops.length + 1}`; const stop = { id, name: `${mode} ${network.definition.stops.length + 1}`, coordinate, kind: mode === 'SUBWAY' ? 'station' as const : 'stop' as const, supportedModes: [mode] }; setNetwork(createStop(network, stop)); setSelectedStops((current) => [...current, id]); setMessage(`Created ${stop.name}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create stop'); } }, [coordinate, mode, network, placementEnabled]);
  const toggleStop = (id: string): void => setSelectedStops((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const createNewLine = (): void => { try { const id = `line-${network.definition.lines.length + 1}`; const line = makeLine(id, lineName.trim() || `Line ${network.definition.lines.length + 1}`, mode, selectedStops, network); setNetwork(createLine(network, line)); setSelectedLineId(id); setMessage(`Created ${line.name}.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create line'); } };
  const selectedLine = network.getLine(selectedLineId); const graph = new TransitGraph(network);
  return <section className="transit-debug"><p className="eyebrow">TRANSIT NETWORK DEBUG</p><h2>Topology editor</h2><label>Mode <select aria-label="Transit mode" value={mode} onChange={(event) => setMode(event.target.value as TransitMode)}><option value="BUS">Bus</option><option value="TRAM">Tram</option><option value="SUBWAY">Subway</option></select></label><label><input type="checkbox" checked={placementEnabled} onChange={(event) => setPlacementEnabled(event.target.checked)} /> Click map to create stops</label><p className="debug-note">{message}</p><h3>Stops ({network.definition.stops.length})</h3><ul className="network-list">{network.definition.stops.map((stop) => <li key={stop.id}><label><input type="checkbox" checked={selectedStops.includes(stop.id)} onChange={() => toggleStop(stop.id)} /> {stop.name} <small>({stop.supportedModes.join('/')})</small></label></li>)}</ul><label>Line name <input aria-label="Transit line name" value={lineName} onChange={(event) => setLineName(event.target.value)} /></label><button type="button" onClick={createNewLine}>Create line from selected stops</button><button type="button" onClick={() => { try { const id = `transfer-${network.definition.transferComplexes.length + 1}`; setNetwork(createTransferComplex(network, id, `Transfer ${network.definition.transferComplexes.length + 1}`, selectedStops)); setMessage('Created transfer complex.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Select two or more stops'); } }}>Create transfer complex</button><h3>Lines ({network.definition.lines.length})</h3><select aria-label="Selected transit line" value={selectedLineId} onChange={(event) => setSelectedLineId(event.target.value)}><option value="">Select a line</option>{network.definition.lines.map((line) => <option value={line.id} key={line.id}>{line.name} ({line.mode})</option>)}</select>{selectedLine && <div className="line-actions"><p>{selectedLine.stopIds.length} stops · {selectedLine.segments.length} segments · {graph.componentFor(selectedLine.stopIds[0]).length} connected nodes</p><button type="button" onClick={() => { const name = lineName.trim(); if (name) setNetwork(renameLine(network, selectedLine.id, name)); }}>Rename selected</button><button type="button" onClick={() => { setNetwork(deleteLine(network, selectedLine.id)); setSelectedLineId(''); }}>Delete selected</button></div>}<button type="button" className="reset-network" onClick={() => { setNetwork(new TransitNetwork()); setSelectedStops([]); setSelectedLineId(''); setMessage('Network reset.'); }}>Reset network</button><dl><dt>Lines</dt><dd>{network.definition.lines.length}</dd><dt>Stops</dt><dd>{network.definition.stops.length}</dd><dt>Transfers</dt><dd>{network.definition.transferComplexes.length}</dd><dt>Selected line</dt><dd>{selectedLine?.name ?? 'None'}</dd><dt>Selected stops</dt><dd>{selectedStops.length}</dd></dl></section>;
}
