import { describe, expect, it } from 'vitest';
import { addStopToLine, createLine, createStop, createTransferComplex, deleteLine, deserializeTransitNetwork, getStopsNearCoordinate, makeLine, removeStopFromLine, reorderLineStops, serializeTransitNetwork, TransitGraph, TransitNetwork } from './index';
import type { TransitMode, TransitStop } from './types';

const point = (latitude: number, longitude: number) => ({ latitude, longitude });
const stop = (id: string, coordinate = point(41.88, -87.63), modes: readonly TransitMode[] = ['BUS', 'TRAM', 'SUBWAY']): TransitStop => ({ id, name: id, coordinate, kind: 'stop', supportedModes: modes });
const networkWithStops = (): TransitNetwork => ['a', 'b', 'c', 'd'].reduce((network, id, index) => createStop(network, stop(id, point(41.88 + index * .002, -87.63))), new TransitNetwork());
describe('Transit Network System', () => {
  it('creates stops and validates duplicate IDs and infrastructure proposals', () => { const validator = { validateProposal: () => ({ valid: false, reasons: ['blocked in test'] }) }; expect(() => createStop(new TransitNetwork(), stop('a'), validator)).toThrow(/blocked in test/); const network = createStop(new TransitNetwork(), stop('a')); expect(network.getStop('a')?.supportedModes).toEqual(['BUS', 'TRAM', 'SUBWAY']); expect(() => createStop(network, stop('a'))).toThrow(/Duplicate stop ID/); });
  it('creates, orders, adds to, and removes from a line', () => { let network = networkWithStops(); const line = makeLine('blue', 'Blue Line', 'TRAM', ['a', 'b', 'c'], network); network = createLine(network, line); expect(network.getLine('blue')?.segments.map((segment) => segment.id)).toEqual(['blue-segment-1', 'blue-segment-2']); network = reorderLineStops(network, 'blue', ['c', 'b', 'a']); expect(network.getLine('blue')?.stopIds).toEqual(['c', 'b', 'a']); network = addStopToLine(network, 'blue', 'd', 1); expect(network.getLine('blue')?.stopIds).toEqual(['c', 'd', 'b', 'a']); network = removeStopFromLine(network, 'blue', 'd'); expect(network.getLine('blue')?.stopIds).toEqual(['c', 'b', 'a']); });
  it('rejects invalid references and incompatible line stops', () => { const network = createStop(new TransitNetwork(), stop('bus-only', point(1, 1), ['BUS'])); expect(() => createLine(network, makeLine('tram', 'Tram', 'TRAM', ['bus-only', 'missing'], network))).toThrow(); });
  it('serializes and restores versioned stable network data', () => { let network = networkWithStops(); network = createLine(network, makeLine('green', 'Green', 'TRAM', ['a', 'b'], network)); const restored = deserializeTransitNetwork(serializeTransitNetwork(network)); expect(restored.definition).toEqual(network.definition); expect(restored.getLine('green')?.mode).toBe('TRAM'); });
  it('detects transfers and graph connectivity while preserving disconnected components', () => { let network = networkWithStops(); network = createLine(network, makeLine('bus', 'Bus', 'BUS', ['a', 'b'], network)); network = createLine(network, makeLine('tram', 'Tram', 'TRAM', ['c', 'd'], network)); expect(new TransitGraph(network).componentFor('a')).toEqual(['a', 'b']); network = createTransferComplex(network, 'central', 'Central', ['b', 'c']); const graph = new TransitGraph(network); expect(graph.transfers('b').map((edge) => edge.toStopId)).toContain('c'); expect(graph.directlyConnected('a', 'b')).toBe(true); expect(graph.componentFor('a')).toEqual(['a', 'b', 'c', 'd']); expect(getStopsNearCoordinate(network, point(41.88, -87.63), 20).map((item) => item.id)).toEqual(['a']); });
  it('cleans up line state on deletion without deleting infrastructure', () => { let network = networkWithStops(); network = createLine(network, makeLine('bus', 'Bus', 'BUS', ['a', 'b'], network)); network = deleteLine(network, 'bus'); expect(network.definition.lines).toHaveLength(0); expect(network.definition.stops).toHaveLength(4); });
});
