import { describe, expect, it } from 'vitest';
import { ModeRegistry, modeRegistry, validateServiceFrequency } from './index';
import type { TransportModeDefinition, VehicleDefinition } from './types';

describe('Transportation Modes', () => {
  it('lists and looks up the three prototype modes with distinct characteristics', () => { expect(modeRegistry.listModeDefinitions().map((mode) => mode.id)).toEqual(['BUS', 'TRAM', 'SUBWAY']); expect(modeRegistry.getModeDefinition('BUS').infrastructure.constrainedToRoads).toBe(true); expect(modeRegistry.getModeDefinition('TRAM').infrastructure.requiresConstructedAlignment).toBe(true); expect(modeRegistry.getModeDefinition('SUBWAY').infrastructure.requiresStation).toBe(true); expect(modeRegistry.getVehicleDefinitionsForMode('SUBWAY')[0].capacity).toBeGreaterThan(modeRegistry.getVehicleDefinitionsForMode('BUS')[0].capacity); expect(modeRegistry.getModeDefinition('BUS').operations.defaultFare.fareCents).toBe(250); expect(() => modeRegistry.getModeDefinition('UNKNOWN')).toThrow(/Unknown transportation mode/); });
  it('validates reusable day/night frequency configuration', () => { expect(() => validateServiceFrequency({ daytimeHeadwayMinutes: 0, nighttimeHeadwayMinutes: 20, daytimeStartHour: 6, nighttimeStartHour: 22 })).toThrow(/positive/); expect(() => validateServiceFrequency({ daytimeHeadwayMinutes: 2, nighttimeHeadwayMinutes: 20, daytimeStartHour: 6, nighttimeStartHour: 22 }, 3)).toThrow(/at least/); });
  it('registers an additional mode without core branching or non-serializable IDs', () => { const definition: TransportModeDefinition = { id: 'TEST_MODE', name: 'Test Mode', symbol: 'X', color: '#000', summary: 'Test-only extension.', infrastructure: { kind: 'dedicated-guideway', requiresConstructedAlignment: true, requiresStation: false, constrainedToRoads: false }, operations: { defaultCruisingSpeedKph: 40, defaultDwellSeconds: 20, minimumHeadwayMinutes: 5, defaultFrequency: { daytimeHeadwayMinutes: 10, nighttimeHeadwayMinutes: 20, daytimeStartHour: 6, nighttimeStartHour: 22 }, defaultFare: { kind: 'flat-boarding', fareCents: 100, freeTransfers: false } }, vehicleIds: ['test-vehicle'] }; const vehicle: VehicleDefinition = { id: 'test-vehicle', modeId: 'TEST_MODE', name: 'Test Vehicle', capacity: 50, maximumSpeedKph: 60, operatingCostPerHour: 10, purchaseCost: 50_000, dwellTimeModifier: 1 }; const registry = new ModeRegistry().register(definition, [vehicle]); expect(registry.getModeDefinition('TEST_MODE').id).toBe('TEST_MODE'); expect(registry.getVehicleDefinitionsForMode('TEST_MODE')[0].modeId).toBe('TEST_MODE'); });
});
