import type { ModeId, TransportModeDefinition, VehicleDefinition, ServiceFrequency } from './types';

export function validateServiceFrequency(frequency: ServiceFrequency, minimumHeadwayMinutes = 0): void { if (!Number.isFinite(frequency.daytimeHeadwayMinutes) || !Number.isFinite(frequency.nighttimeHeadwayMinutes) || frequency.daytimeHeadwayMinutes <= 0 || frequency.nighttimeHeadwayMinutes <= 0) throw new Error('Daytime and nighttime headways must be positive.'); if (frequency.daytimeHeadwayMinutes < minimumHeadwayMinutes || frequency.nighttimeHeadwayMinutes < minimumHeadwayMinutes) throw new Error(`Headways must be at least ${minimumHeadwayMinutes} minutes.`); if (![frequency.daytimeStartHour, frequency.nighttimeStartHour].every((hour) => Number.isInteger(hour) && hour >= 0 && hour <= 23)) throw new Error('Service period boundaries must be whole hours from 0 through 23.'); }
/** Registry centralizes mode knowledge; consumers retain serializable string IDs only. */
export class ModeRegistry {
  private readonly modes = new Map<ModeId, TransportModeDefinition>(); private readonly vehicles = new Map<string, VehicleDefinition>();
  public register(definition: TransportModeDefinition, vehicles: readonly VehicleDefinition[]): this { if (!definition.id.trim() || this.modes.has(definition.id)) throw new Error(`Duplicate or empty mode ID "${definition.id}"`); validateServiceFrequency(definition.operations.defaultFrequency, definition.operations.minimumHeadwayMinutes); if (vehicles.some((vehicle) => vehicle.modeId !== definition.id || vehicle.capacity <= 0 || vehicle.maximumSpeedKph <= 0 || vehicle.operatingCostPerHour < 0)) throw new Error(`Invalid vehicle configuration for mode "${definition.id}"`); if (new Set(vehicles.map((vehicle) => vehicle.id)).size !== vehicles.length || definition.vehicleIds.some((id) => !vehicles.some((vehicle) => vehicle.id === id))) throw new Error(`Mode "${definition.id}" references invalid vehicle IDs`); this.modes.set(definition.id, definition); vehicles.forEach((vehicle) => this.vehicles.set(vehicle.id, vehicle)); return this; }
  public getModeDefinition(id: ModeId): TransportModeDefinition { const mode = this.modes.get(id); if (!mode) throw new Error(`Unknown transportation mode "${id}"`); return mode; }
  public listModeDefinitions(): readonly TransportModeDefinition[] { return [...this.modes.values()]; }
  public getVehicleDefinitionsForMode(id: ModeId): readonly VehicleDefinition[] { const mode = this.getModeDefinition(id); return mode.vehicleIds.map((vehicleId) => this.vehicles.get(vehicleId)!).filter(Boolean); }
  public getVehicleDefinition(id: string): VehicleDefinition { const vehicle = this.vehicles.get(id); if (!vehicle) throw new Error(`Unknown vehicle type "${id}"`); return vehicle; }
}
