import { describe, expect, it } from 'vitest';
import { Economy } from './Economy';
import { modeRegistry } from '../modes';

describe('Economy', () => {
  it('starts from the level budget and debits affordable construction atomically', () => { const economy = new Economy(100); expect(economy.getCurrentCash()).toBe(10_000); expect(economy.recordConstruction({ cost: { baseInfrastructure: 60, depthSurcharge: 0, riverEngineering: 0, demolition: 0, total: 60 }, demolitionImpacts: [], riverCrossingIds: [], horizontalLengthMeters: 0 }, 0)).toBe(true); expect(economy.getCurrentCash()).toBe(4_000); expect(economy.recordConstruction({ cost: { baseInfrastructure: 50, depthSurcharge: 0, riverEngineering: 0, demolition: 0, total: 50 }, demolitionImpacts: [], riverCrossingIds: [], horizontalLengthMeters: 0 }, 0)).toBe(false); expect(economy.getCurrentCash()).toBe(4_000); });
  it('purchases an affordable vehicle as a durable ledger transaction', () => { const economy = new Economy(1_000_000); const vehicle = modeRegistry.getVehicleDefinition('standard-bus'); expect(economy.purchaseVehicle(vehicle, 120, 'bus-1')).toBe(true); expect(economy.getLedger().at(-1)).toMatchObject({ category: 'VEHICLE_PURCHASE', relatedEntityId: 'bus-1', amountCents: -vehicle.purchaseCost * 100 }); });
  it('aggregates fares and operating expenses by line/hour and permits negative operating cash', () => { const economy = new Economy(1); economy.consumeOperationsEvents([{ type: 'FARE_CHARGED', lineId: 'red', vehicleId: 'v1', passengerId: 'p1', amountCents: 250, timestampSeconds: 61 }, { type: 'FARE_CHARGED', lineId: 'red', vehicleId: 'v2', passengerId: 'p2', amountCents: 250, timestampSeconds: 3599 }, { type: 'VEHICLE_OPERATING_COST', lineId: 'red', vehicleId: 'v1', amountCents: 900, timestampSeconds: 62 }]); expect(economy.getLedger()).toHaveLength(3); expect(economy.getCurrentCash()).toBe(-300); const line = economy.getFinancialSummary(0).lines[0]; expect(line).toMatchObject({ lineId: 'red', boardings: 2, fareRevenueCents: 500, operatingCostCents: 900, netOperatingCents: -400 }); });
  it('records loan proceeds, scheduled interest and repayment, then restores exactly', () => { const economy = new Economy(0); const loan = economy.takeLoan('small-expansion', 0); expect(economy.getCurrentCash()).toBe(loan.principalCents); economy.processScheduledPayments(loan.nextPaymentAtSeconds); expect(economy.getLedger().some((entry) => entry.category === 'LOAN_INTEREST')).toBe(true); expect(economy.getLoans()[0].outstandingCents).toBeLessThan(loan.principalCents); const restored = Economy.restore(economy.serialize()); expect(restored.getFinancialSummary()).toEqual(economy.getFinancialSummary()); });
});
