import type { ConstructionEstimate } from '../construction';
import type { OperationsEvent } from '../operations';
import { standardLoanProducts } from './config';
import type { ActiveLoan, EconomyState, FinancialPeriod, FinancialSummary, LedgerTransaction, LineEconomics } from './types';

const daySeconds = 86_400;
const emptyPeriod = (): FinancialPeriod => ({ cashCents: 0, fareRevenueCents: 0, operatingCostCents: 0, constructionSpendingCents: 0, demolitionSpendingCents: 0, netOperatingCents: 0 });
const requireCents = (amount: number): void => { if (!Number.isSafeInteger(amount)) throw new Error('Economic amounts must be safe integer cents.'); };
const copyState = (state: EconomyState): EconomyState => ({ version: 1, startingCashCents: state.startingCashCents, ledger: [...state.ledger], loans: [...state.loans] });

/** Ledger-first finance authority. It owns money only; other systems retain their own domain state. */
export class Economy {
  private state: EconomyState;
  private transactionSequence: number;
  public constructor(startingBudgetDollars: number, state?: EconomyState) {
    if (state) { this.state = copyState(state); this.transactionSequence = state.ledger.length; return; }
    if (!Number.isFinite(startingBudgetDollars) || startingBudgetDollars < 0) throw new Error('Starting budget must be a nonnegative finite dollar amount.');
    const startingCashCents = Math.round(startingBudgetDollars * 100);
    this.state = { version: 1, startingCashCents, ledger: [{ id: 'starting-balance', timestampSeconds: 0, amountCents: startingCashCents, category: 'STARTING_BALANCE', description: 'Level starting balance' }], loans: [] };
    this.transactionSequence = 1;
  }
  public getCurrentCash(): number { return this.state.ledger.reduce((sum, transaction) => sum + transaction.amountCents, 0); }
  public canAfford(costCents: number): boolean { requireCents(costCents); return costCents >= 0 && this.getCurrentCash() >= costCents; }
  public record(input: Omit<LedgerTransaction, 'id'>): LedgerTransaction { requireCents(input.amountCents); if (!Number.isFinite(input.timestampSeconds) || input.timestampSeconds < 0) throw new Error('Transaction timestamp must be nonnegative.'); const transaction = { ...input, id: `txn-${this.transactionSequence++}` }; this.state = { ...this.state, ledger: [...this.state.ledger, transaction] }; return transaction; }
  public recordConstruction(estimate: ConstructionEstimate, timestampSeconds: number, relatedEntityId?: string): boolean {
    const totalCents = Math.round(estimate.cost.total * 100); if (!this.canAfford(totalCents)) return false;
    const baseCents = Math.round((estimate.cost.baseInfrastructure + estimate.cost.depthSurcharge + estimate.cost.riverEngineering) * 100); const demolitionCents = Math.round(estimate.cost.demolition * 100);
    if (baseCents) this.record({ timestampSeconds, amountCents: -baseCents, category: 'CONSTRUCTION', description: 'Infrastructure construction', relatedEntityId, metadata: { baseInfrastructure: estimate.cost.baseInfrastructure, depthSurcharge: estimate.cost.depthSurcharge, riverEngineering: estimate.cost.riverEngineering } });
    if (demolitionCents) this.record({ timestampSeconds, amountCents: -demolitionCents, category: 'DEMOLITION', description: 'Acquisition and demolition', relatedEntityId, metadata: { buildings: estimate.demolitionImpacts.length } });
    return true;
  }
  /** Groups incoming operational events by category, line, and simulated hour to bound ledger growth. */
  public consumeOperationsEvents(events: readonly OperationsEvent[]): void {
    const grouped = new Map<string, { amountCents: number; count: number; event: OperationsEvent }>();
    for (const event of events) { const hour = Math.floor(event.timestampSeconds / 3600); const key = `${event.type}:${event.lineId}:${hour}`; const previous = grouped.get(key); grouped.set(key, { amountCents: (previous?.amountCents ?? 0) + event.amountCents, count: (previous?.count ?? 0) + 1, event }); }
    for (const { amountCents, count, event } of grouped.values()) this.record({ timestampSeconds: Math.floor(event.timestampSeconds / 3600) * 3600, amountCents: event.type === 'FARE_CHARGED' ? amountCents : -amountCents, category: event.type === 'FARE_CHARGED' ? 'FARE_REVENUE' : 'OPERATING_COST', description: event.type === 'FARE_CHARGED' ? `Aggregated fares (${count} boardings)` : `Aggregated vehicle operations (${count} entries)`, relatedEntityId: event.lineId, metadata: event.type === 'FARE_CHARGED' ? { boardings: count } : { vehicleEvents: count } });
  }
  public takeLoan(productId: string, timestampSeconds: number): ActiveLoan { const product = standardLoanProducts.find((item) => item.id === productId); if (!product) throw new Error(`Unknown loan product "${productId}".`); const loan: ActiveLoan = { id: `loan-${this.state.loans.length + 1}`, productId: product.id, principalCents: product.principalCents, annualInterestRate: product.annualInterestRate, outstandingCents: product.principalCents, issuedAtSeconds: timestampSeconds, nextPaymentAtSeconds: timestampSeconds + product.paymentIntervalSeconds, paymentIntervalSeconds: product.paymentIntervalSeconds, paymentCents: product.paymentCents }; this.state = { ...this.state, loans: [...this.state.loans, loan] }; this.record({ timestampSeconds, amountCents: product.principalCents, category: 'LOAN_PROCEEDS', description: product.name, relatedEntityId: loan.id }); return loan; }
  public processScheduledPayments(timestampSeconds: number): void { let loans = [...this.state.loans]; for (const loan of loans) { let current = loan; while (current.outstandingCents > 0 && current.nextPaymentAtSeconds <= timestampSeconds) { const interest = Math.round(current.outstandingCents * current.annualInterestRate * current.paymentIntervalSeconds / (365 * daySeconds)); const principal = Math.min(current.outstandingCents, Math.max(0, current.paymentCents - interest)); this.record({ timestampSeconds: current.nextPaymentAtSeconds, amountCents: -interest, category: 'LOAN_INTEREST', description: 'Scheduled loan interest', relatedEntityId: current.id }); if (principal) this.record({ timestampSeconds: current.nextPaymentAtSeconds, amountCents: -principal, category: 'LOAN_PAYMENT', description: 'Scheduled loan principal payment', relatedEntityId: current.id }); current = { ...current, outstandingCents: current.outstandingCents - principal, nextPaymentAtSeconds: current.nextPaymentAtSeconds + current.paymentIntervalSeconds }; } loans = loans.map((item) => item.id === current.id ? current : item); } this.state = { ...this.state, loans: loans.filter((loan) => loan.outstandingCents > 0) }; }
  public getFinancialSummary(timestampSeconds = 0): FinancialSummary { const summarize = (transactions: readonly LedgerTransaction[]): FinancialPeriod => transactions.reduce((period, transaction) => ({ cashCents: period.cashCents + transaction.amountCents, fareRevenueCents: period.fareRevenueCents + (transaction.category === 'FARE_REVENUE' ? transaction.amountCents : 0), operatingCostCents: period.operatingCostCents + (transaction.category === 'OPERATING_COST' ? -transaction.amountCents : 0), constructionSpendingCents: period.constructionSpendingCents + (transaction.category === 'CONSTRUCTION' ? -transaction.amountCents : 0), demolitionSpendingCents: period.demolitionSpendingCents + (transaction.category === 'DEMOLITION' ? -transaction.amountCents : 0), netOperatingCents: period.netOperatingCents + (transaction.category === 'FARE_REVENUE' || transaction.category === 'OPERATING_COST' ? transaction.amountCents : 0) }), emptyPeriod()); const todayStart = Math.floor(timestampSeconds / daySeconds) * daySeconds; const byLine = new Map<string, LineEconomics>(); for (const transaction of this.state.ledger) if (transaction.relatedEntityId && (transaction.category === 'FARE_REVENUE' || transaction.category === 'OPERATING_COST')) { const entry = byLine.get(transaction.relatedEntityId) ?? { lineId: transaction.relatedEntityId, boardings: 0, fareRevenueCents: 0, operatingCostCents: 0, netOperatingCents: 0 }; const fare = transaction.category === 'FARE_REVENUE' ? transaction.amountCents : 0; const cost = transaction.category === 'OPERATING_COST' ? -transaction.amountCents : 0; byLine.set(entry.lineId, { ...entry, boardings: entry.boardings + (typeof transaction.metadata?.boardings === 'number' ? transaction.metadata.boardings : 0), fareRevenueCents: entry.fareRevenueCents + fare, operatingCostCents: entry.operatingCostCents + cost, netOperatingCents: entry.netOperatingCents + fare - cost }); } return { cashCents: this.getCurrentCash(), debtCents: this.state.loans.reduce((sum, loan) => sum + loan.outstandingCents, 0), today: summarize(this.state.ledger.filter((transaction) => transaction.timestampSeconds >= todayStart)), allTime: summarize(this.state.ledger), lines: [...byLine.values()] }; }
  public getLedger(): readonly LedgerTransaction[] { return this.state.ledger; }
  public getLoans(): readonly ActiveLoan[] { return this.state.loans; }
  public serialize(): EconomyState { return copyState(this.state); }
  public static restore(state: EconomyState): Economy { return new Economy(state.startingCashCents / 100, state); }
}
