import { useState } from 'react';
import { standardLoanProducts } from './config';
import type { Economy } from './Economy';

const money = (cents: number): string => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(cents / 100);
export function FinancePanel({ economy, timestampSeconds, onChange }: { readonly economy: Economy; readonly timestampSeconds: number; readonly onChange: () => void }) {
  const [open, setOpen] = useState(false); const summary = economy.getFinancialSummary(timestampSeconds); const borrow = (id: string): void => { economy.takeLoan(id, timestampSeconds); onChange(); };
  return <section className="finance-panel"><p className="eyebrow">ECONOMY</p><h2>Cash {money(summary.cashCents)}</h2><p className="finance-kpis">Today: {money(summary.today.cashCents)} · Debt: {money(summary.debtCents)}</p><button type="button" onClick={() => setOpen((value) => !value)}>{open ? 'Close finance' : 'Open finance'}</button>{open && <><dl><dt>Fare revenue</dt><dd>{money(summary.today.fareRevenueCents)}</dd><dt>Operating costs</dt><dd>{money(summary.today.operatingCostCents)}</dd><dt>Construction</dt><dd>{money(summary.today.constructionSpendingCents)}</dd><dt>Demolition</dt><dd>{money(summary.today.demolitionSpendingCents)}</dd><dt>Net operations</dt><dd>{money(summary.today.netOperatingCents)}</dd></dl><h3>Loans</h3>{standardLoanProducts.map((loan) => <button key={loan.id} type="button" onClick={() => borrow(loan.id)}>Borrow {money(loan.principalCents)} — {loan.name}</button>)}<h3>Recent activity</h3><ul className="finance-ledger">{economy.getLedger().slice(-6).reverse().map((entry) => <li key={entry.id}><span>{entry.description}</span><strong className={entry.amountCents < 0 ? 'expense' : 'credit'}>{entry.amountCents < 0 ? '−' : '+'}{money(Math.abs(entry.amountCents))}</strong></li>)}</ul>{summary.lines.map((line) => <p className="debug-note" key={line.lineId}>{line.lineId}: {line.boardings} boardings, {money(line.netOperatingCents)} net operations</p>)}</>}</section>;
}
