import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { dispatch, makeId, newRoute, newStation, scoreParts, seedSession } from './session';
import { saveSession } from './save';
import type { PlannerCommand, PlannerSession, Tool } from './types';

type Props = { cityId: string; cityName: string; initial?: PlannerSession; onExit(): void };
const icons: Record<Tool, string> = { select: '⌁', bus: 'B', tram: 'T', subway: 'S', station: '+', data: '◫' };
const money = (value: number): string => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const time = (minutes: number): string => `${String(Math.floor(minutes / 60) % 24).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`;

export function Planner({ cityId, cityName, initial, onExit }: Props) {
  const [session, setSession] = useState<PlannerSession>(() => initial ?? seedSession(cityId, cityName));
  const [tool, setTool] = useState<Tool>('select'); const [panel, setPanel] = useState<'inspector' | 'network' | 'analysis' | 'finance'>('inspector');
  const [history, setHistory] = useState<PlannerSession[]>([]); const [future, setFuture] = useState<PlannerSession[]>([]); const [notice, setNotice] = useState('All changes save automatically.');
  const [confirm, setConfirm] = useState<string | null>(null); const [pinned, setPinned] = useState(false); const lastSaved = useRef(session.updatedAt);
  const run = useCallback((command: PlannerCommand) => { const result = dispatch(session, command); if (!result.ok) { setNotice(result.message); return; } setHistory((h) => [...h.slice(-39), session]); setFuture([]); setSession(result.session); }, [session]);
  useEffect(() => { const timer = window.setTimeout(() => { if (lastSaved.current !== session.updatedAt) { saveSession(session); lastSaved.current = session.updatedAt; setNotice('Saved to this device.'); } }, 650); return () => window.clearTimeout(timer); }, [session]);
  useEffect(() => { const timer = window.setInterval(() => { if (session.speed) setSession((current) => ({ ...current, clock: current.clock + current.speed, updatedAt: current.updatedAt })); }, 1000); return () => window.clearInterval(timer); }, [session.speed]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); if (event.shiftKey) redo(); else undo(); } if (!event.metaKey && !event.ctrlKey && !event.altKey) { const map: Record<string, Tool> = { v: 'select', b: 'bus', t: 'tram', s: 'subway', n: 'station', d: 'data' }; if (map[event.key.toLowerCase()]) setTool(map[event.key.toLowerCase()]); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); });
  const undo = () => setHistory((h) => { const previous = h.at(-1); if (!previous) return h; setFuture((f) => [session, ...f]); setSession(previous); return h.slice(0, -1); });
  const redo = () => setFuture((f) => { const next = f[0]; if (!next) return f; setHistory((h) => [...h, session]); setSession(next); return f.slice(1); });
  const place = (event: React.MouseEvent<HTMLDivElement>) => { const box = event.currentTarget.getBoundingClientRect(); const x = Math.round(((event.clientX - box.left) / box.width) * 100); const y = Math.round(((event.clientY - box.top) / box.height) * 100); if (tool === 'station') { run({ type: 'station.create', station: newStation(x, y) }); setPanel('inspector'); } else if (tool === 'bus' || tool === 'tram' || tool === 'subway') { const route = newRoute(tool); run({ type: 'route.create', route: { ...route, stops: session.stations.length ? [session.stations[0].id] : [] } }); setNotice(`${route.name} draft created. Select it in Network to edit service.`); setPanel('network'); } else run({ type: 'select', id: undefined }); };
  const selected = useMemo(() => [...session.routes, ...session.stations, ...session.projects].find((entity) => entity.id === session.selectedId), [session]);
  const startProject = () => { const project = { id: makeId('project'), label: 'Civic Center interchange', cost: 185000, status: 'draft' as const }; run({ type: 'project.create', project }); setConfirm(project.id); };
  const tools: Tool[] = ['select', 'bus', 'tram', 'subway', 'station', 'data'];
  return <main className="planner-shell"><header className="hud"><div className="brand"><span className="brand-mark">OT</span><span>OpenTransport</span></div><div className="hud-city"><small>ACTIVE CITY</small><strong>{session.cityName}</strong></div><div className="hud-metrics"><span><small>TIME</small>{time(session.clock)}</span><span><small>SCORE</small>{session.score.toLocaleString()}</span><span><small>CASH</small>{money(session.cash)}</span></div><div className="speed" aria-label="Simulation speed"><button onClick={() => run({ type: 'clock.set', speed: 0 })} aria-label="Pause simulation">Ⅱ</button>{([1,2,3] as const).map((speed) => <button key={speed} className={session.speed === speed ? 'active' : ''} onClick={() => run({ type: 'clock.set', speed })}>{speed}×</button>)}</div><button className="quiet" onClick={() => { saveSession(session); setNotice('Saved to this device.'); }}>Save</button><button className="quiet" onClick={() => setConfirm('exit')}>Exit</button></header>
    <div className="workspace"><nav className="tool-rail" aria-label="Planning tools">{tools.map((item) => <button key={item} className={tool === item ? 'active' : ''} onClick={() => setTool(item)} title={`${item} tool`} aria-label={`${item} tool`}><b>{icons[item]}</b><span>{item}</span></button>)}<i /><button onClick={undo} disabled={!history.length} aria-label="Undo (Ctrl Z)">↶<span>undo</span></button><button onClick={redo} disabled={!future.length} aria-label="Redo (Ctrl Shift Z)">↷<span>redo</span></button></nav>
      <section className="fixture-map" onClick={place} aria-label="Interactive planning canvas"><div className="map-grid" /><div className="map-water water-a"/><div className="map-water water-b"/><div className="neighborhood n1">OLD PORT</div><div className="neighborhood n2">CIVIC DISTRICT</div><div className="neighborhood n3">EAST MARKET</div>{session.routes.filter((r) => r.visible).map((route, index) => <div key={route.id} className="route-stroke" style={{ '--route': route.color, '--offset': `${index * 19 - 10}px` } as React.CSSProperties} onClick={(e) => { e.stopPropagation(); run({ type: 'select', id: route.id }); }}><span style={{ background: route.color }}>{route.name}</span></div>)}{session.stations.map((station) => <button key={station.id} className={`station-dot ${session.selectedId === station.id ? 'selected' : ''}`} style={{ left: `${station.x}%`, top: `${station.y}%` }} onClick={(e) => { e.stopPropagation(); run({ type: 'select', id: station.id }); }} aria-label={`Select ${station.name}`}><i /></button>)}{Object.entries(session.overlays).filter(([, enabled]) => enabled).map(([name]) => <div className={`heat heat-${name}`} key={name} />)}<div className="map-status"><span className="live-dot"/> Fixture city canvas <em>Map adapter ready</em></div><div className="map-controls"><button onClick={(e) => { e.stopPropagation(); run({ type: 'camera.set', camera: { ...session.camera, zoom: session.camera.zoom + .2 } }); }}>+</button><button onClick={(e) => { e.stopPropagation(); run({ type: 'camera.set', camera: { ...session.camera, zoom: Math.max(.6, session.camera.zoom - .2) } }); }}>−</button><button onClick={(e) => { e.stopPropagation(); run({ type: 'camera.set', camera: { zoom: 1, tilt: 0, x: 0, y: 0 } }); }}>Reset</button></div></section>
      <aside className={`context-panel ${pinned ? 'pinned' : ''}`}><div className="panel-tabs">{(['inspector','network','analysis','finance'] as const).map((tab) => <button key={tab} className={panel === tab ? 'active' : ''} onClick={() => setPanel(tab)}>{tab}</button>)}<button onClick={() => setPinned(!pinned)} aria-label="Pin panel">⌖</button></div><Panel panel={panel} session={session} selected={selected} run={run} onProject={startProject}/></aside>
    </div><footer className="statusbar"><span role="status">{notice}</span><span>{tool === 'station' ? 'Click the canvas to place a station' : tool === 'select' ? 'Select a route or station to inspect it' : `Click canvas to draft a ${tool} line`}</span></footer>
    {!session.tutorial.dismissed && <Tutorial session={session} run={run}/>} {confirm && <Dialog title={confirm === 'exit' ? 'Leave this plan?' : 'Start construction?'} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm === 'exit') onExit(); else run({ type: 'project.confirm', id: confirm }); setConfirm(null); }}>{confirm === 'exit' ? 'Your latest changes are saved locally. You can continue this city anytime.' : 'This will reserve $185,000 and begin the Civic Center interchange project.'}</Dialog>}
  </main>;
}
function Panel({ panel, session, selected, run, onProject }: { panel: string; session: PlannerSession; selected: { id: string; name?: string; label?: string } | undefined; run(command: PlannerCommand): void; onProject(): void }) { if (panel === 'network') return <div className="panel-body"><h2>Network</h2><p className="muted">{session.routes.length} lines · {session.stations.length} stations</p>{session.routes.map((route) => <article className="route-card" key={route.id} onClick={() => run({ type: 'select', id: route.id })}><i style={{ background: route.color }}/><div><strong>{route.name}</strong><small>{route.mode} · {route.vehicles} vehicles · every {route.headway} min</small></div><button className="icon-btn" onClick={(e) => { e.stopPropagation(); run({ type: 'route.update', id: route.id, changes: { visible: !route.visible } }); }} aria-label="Toggle route visibility">◉</button></article>)}<button className="wide-action" onClick={onProject}>Plan construction</button></div>; if (panel === 'analysis') return <div className="panel-body"><h2>City analysis</h2><p className="muted">Visualize needs before you build.</p>{Object.entries(session.overlays).map(([name, enabled]) => <label className="toggle" key={name}><span><strong>{name.replace('-', ' ')}</strong><small>Show on map</small></span><input type="checkbox" checked={enabled} onChange={() => run({ type: 'overlay.toggle', overlay: name as keyof PlannerSession['overlays'] })}/></label>)}</div>; if (panel === 'finance') return <div className="panel-body"><h2>Finance</h2><div className="finance-total">{money(session.cash)}<small>available cash</small></div>{[['Construction', '$185,000'], ['Operations', `$${session.routes.length * 24},600 / wk`], ['Fare revenue', `$${session.routes.length * 31},200 / wk`], ['Debt', '$0']].map(([label, value]) => <div className="line-metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}<h3>Score breakdown</h3>{scoreParts(session).map((part) => <div className="line-metric" key={part.label}><span>{part.label}</span><strong>{part.value}</strong></div>)}</div>; return <div className="panel-body"><p className="eyebrow">INSPECTOR</p><h2>{selected?.name ?? selected?.label ?? 'Nothing selected'}</h2>{selected ? <><p className="muted">This item is ready for planning actions. Use the Network tab to tune service and visibility.</p><button className="wide-action" onClick={() => run({ type: 'select', id: undefined })}>Clear selection</button></> : <><p className="muted">Choose a route or station on the canvas. Switch tools to add a new transit line or station.</p><div className="empty-icon">⌁</div></>}</div>; }
function Tutorial({ session, run }: { session: PlannerSession; run(command: PlannerCommand): void }) { const steps = ['Choose a planning tool', 'Place a station or draft a line', 'Review city analysis', 'Save your growing network']; const index = Math.min(session.tutorial.current, steps.length - 1); return <section className="tutorial"><div><p className="eyebrow">FIRST PLAN · {index + 1}/{steps.length}</p><strong>{steps[index]}</strong><p>{index === 0 ? 'Tools change what a click on the city canvas does.' : 'Build a useful network one clear decision at a time.'}</p></div><button onClick={() => run({ type: 'tutorial.set', tutorial: { ...session.tutorial, current: Math.min(index + 1, steps.length - 1), completed: [...new Set([...session.tutorial.completed, index])] } })}>Next</button><button className="quiet" onClick={() => run({ type: 'tutorial.set', tutorial: { ...session.tutorial, dismissed: true } })}>Dismiss</button></section>; }
function Dialog({ title, children, onCancel, onConfirm }: { title: string; children: React.ReactNode; onCancel(): void; onConfirm(): void }) { return <div className="dialog-backdrop" role="presentation"><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2><p>{children}</p><div><button className="quiet" onClick={onCancel}>Cancel</button><button onClick={onConfirm}>Confirm</button></div></section></div>; }
