import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { levelRegistry } from '../levels/manifest';
import type { World } from '../world';
import { LocalStorageSaveRepository, type GameSave } from '../game';

// The city picker stays lightweight; MapLibre and simulation UI only load after a city is chosen.
const MapView = lazy(async () => ({ default: (await import('../map/MapView')).MapView }));

type City = { id: string; name: string; description: string; population: string; size: string; difficulty: 'Beginner' | 'Intermediate' | 'Advanced'; accent: string; levelType?: string };
const cities: City[] = [
  { id: 'dallas', name: 'Dallas', description: 'A broad DFW-region sandbox with airports, job centers, suburbs, highways, and the Trinity River.', population: '4.76M', size: 'DFW region', difficulty: 'Advanced', accent: '#f07b4f', levelType: 'REAL-CITY GENERATED' },
  { id: 'boston-downtown', name: 'Boston', description: 'Historic neighborhoods, narrow streets, and an ambitious core.', population: '684,000', size: 'Central district', difficulty: 'Intermediate', accent: '#56c7d9' },
  { id: 'mini-city', name: 'Havenport', description: 'A compact waterfront city that rewards clear connections.', population: '92,000', size: 'Small', difficulty: 'Beginner', accent: '#d28cff' },
  { id: 'test-city', name: 'Northgate', description: 'A dense fixture city for testing future network ideas.', population: '218,000', size: 'Medium', difficulty: 'Advanced', accent: '#f2a548' }
];
export function App() { const [city, setCity] = useState<City | null>(null); const [world, setWorld] = useState<World>(); const [saved, setSaved] = useState<Record<string, boolean>>({}); const [legacy, setLegacy] = useState<Record<string, boolean>>({}); const [message, setMessage] = useState<string>(); const [replace, setReplace] = useState<City>(); const [legacyReview, setLegacyReview] = useState<City>(); const [initialSave, setInitialSave] = useState<GameSave>(); const saveRepository = useMemo(() => new LocalStorageSaveRepository(), []);
  useEffect(() => { let active = true; void Promise.all(cities.map(async (item) => [item.id, await saveRepository.hasSave(item.id)] as const)).then((entries) => { if (active) setSaved(Object.fromEntries(entries)); }); return () => { active = false; }; }, [saveRepository, city]);
  useEffect(() => setLegacy(Object.fromEntries(cities.map((item) => [item.id, Boolean(localStorage.getItem(`opentransport.planner.${item.id}`))]))), []);
  useEffect(() => { if (!city) { setWorld(undefined); return; } let alive = true; levelRegistry.loadLevel(city.id).then((next) => { if (alive) setWorld(next); }).catch((reason: unknown) => { if (alive) { setMessage(reason instanceof Error ? reason.message : 'Unable to load this city.'); setCity(null); } }); return () => { alive = false; }; }, [city]);
  const open = async (next: City, continueSaved: boolean) => { if (!continueSaved && saved[next.id]) { setReplace(next); return; } try { setInitialSave(continueSaved ? (await saveRepository.load(next.id)) ?? undefined : undefined); } catch { setMessage('This local save could not be restored. Start a fresh plan or replace it.'); setInitialSave(undefined); } setCity(next); };
  if (city) return world ? <Suspense fallback={<main className="city-select"><p className="map-status loading" role="status">Opening {city.name}…</p></main>}><MapView world={world} initialSave={initialSave} onBack={() => { setCity(null); setInitialSave(undefined); }} /></Suspense> : <main className="city-select"><p className="map-status loading" role="status">Loading {city.name}…</p></main>;
  const downloadLegacy = (item: City): void => { const data = localStorage.getItem(`opentransport.planner.${item.id}`); if (!data) return; const url = URL.createObjectURL(new Blob([data], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `${item.id}-legacy-plan.json`; link.click(); URL.revokeObjectURL(url); };
  return <main className="city-select"><header className="city-header"><div className="brand"><span className="brand-mark">OT</span>OpenTransport</div><div><span className="badge">LOCAL PLANNER</span><button className="quiet">Settings</button></div></header><section className="city-intro"><p className="eyebrow">CHOOSE YOUR NEXT CITY</p><h1>Plan a city<br/><em>that moves.</em></h1><p>Design a resilient transit network, respond to demand, and build better daily journeys. Your plans stay on this device.</p></section><section className="city-grid" aria-label="Available cities">{cities.map((item) => <article className="city-card" key={item.id}><div className="city-preview" style={{ '--accent': item.accent } as React.CSSProperties}><span>{item.levelType ?? 'FIXTURE MAP'}</span><i/><i/><i/></div><div className="city-card-copy"><div className="card-heading"><div><p className="eyebrow">{item.difficulty}</p><h2>{item.name}</h2></div>{saved[item.id] && <span className="save-badge">Saved plan</span>}</div><p>{item.description}</p>{legacy[item.id] && <button className="legacy-save" type="button" onClick={() => setLegacyReview(item)}>Legacy plan found</button>}<dl><div><dt>Population</dt><dd>{item.population}</dd></div><div><dt>Map scope</dt><dd>{item.size}</dd></div></dl><div className="city-actions"><button onClick={() => void open(item, false)}>Start fresh <span>→</span></button>{saved[item.id] && <button className="quiet" onClick={() => void open(item, true)}>Continue</button>}</div></div></article>)}</section>{message && <p className="home-message" role="alert">{message}</p>}{replace && <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><h2>Replace saved plan?</h2><p>Starting a fresh {replace.name} plan removes the local save. This cannot be undone.</p><div><button className="quiet" onClick={() => setReplace(undefined)}>Cancel</button><button onClick={() => { localStorage.removeItem(`opentransport:save:${replace.id}`); setSaved((current) => ({ ...current, [replace.id]: false })); setInitialSave(undefined); setCity(replace); setReplace(undefined); }}>Start fresh</button></div></section></div>}{legacyReview && <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><h2>Legacy plan recovery</h2><p>This plan uses the retired fixture-planner format and cannot be safely converted to the live map game. Export a copy, then begin a new current-format session.</p><div><button className="quiet" onClick={() => setLegacyReview(undefined)}>Close</button><button className="secondary" onClick={() => downloadLegacy(legacyReview)}>Export legacy JSON</button><button onClick={() => { localStorage.removeItem(`opentransport.planner.${legacyReview.id}`); setLegacy((current) => ({ ...current, [legacyReview.id]: false })); setInitialSave(undefined); setCity(legacyReview); setLegacyReview(undefined); }}>Start current session</button></div></section></div>}</main>; }
