import { useEffect, useState } from 'react';
import { Planner } from '../planner/Planner';
import { deleteSession, hasSession, loadSession } from '../planner/save';
import type { PlannerSession } from '../planner/types';

type City = { id: string; name: string; description: string; population: string; size: string; difficulty: 'Beginner' | 'Intermediate' | 'Advanced'; accent: string };
const cities: City[] = [
  { id: 'boston-downtown', name: 'Boston', description: 'Historic neighborhoods, narrow streets, and an ambitious core.', population: '684,000', size: 'Central district', difficulty: 'Intermediate', accent: '#56c7d9' },
  { id: 'mini-city', name: 'Havenport', description: 'A compact waterfront city that rewards clear connections.', population: '92,000', size: 'Small', difficulty: 'Beginner', accent: '#d28cff' },
  { id: 'test-city', name: 'Northgate', description: 'A dense fixture city for testing future network ideas.', population: '218,000', size: 'Medium', difficulty: 'Advanced', accent: '#f2a548' }
];
export function App() { const [city, setCity] = useState<City | null>(null); const [session, setSession] = useState<PlannerSession>(); const [saved, setSaved] = useState<Record<string, boolean>>({}); const [message, setMessage] = useState<string>(); const [replace, setReplace] = useState<City>();
  useEffect(() => setSaved(Object.fromEntries(cities.map((item) => [item.id, hasSession(item.id)]))), [city]);
  const open = (next: City, continueSaved: boolean) => { if (!continueSaved && saved[next.id]) { setReplace(next); return; } const result = continueSaved ? loadSession(next.id) : {}; if (result.error) setMessage(result.error); setSession(result.session); setCity(next); };
  if (city) return <Planner cityId={city.id} cityName={city.name} initial={session} onExit={() => { setCity(null); setSession(undefined); }}/>; 
  return <main className="city-select"><header className="city-header"><div className="brand"><span className="brand-mark">OT</span>OpenTransport</div><div><span className="badge">LOCAL PLANNER</span><button className="quiet">Settings</button></div></header><section className="city-intro"><p className="eyebrow">CHOOSE YOUR NEXT CITY</p><h1>Plan a city<br/><em>that moves.</em></h1><p>Design a resilient transit network, respond to demand, and build better daily journeys. Your plans stay on this device.</p></section><section className="city-grid" aria-label="Available cities">{cities.map((item) => <article className="city-card" key={item.id}><div className="city-preview" style={{ '--accent': item.accent } as React.CSSProperties}><span>FIXTURE MAP</span><i/><i/><i/></div><div className="city-card-copy"><div className="card-heading"><div><p className="eyebrow">{item.difficulty}</p><h2>{item.name}</h2></div>{saved[item.id] && <span className="save-badge">Saved plan</span>}</div><p>{item.description}</p><dl><div><dt>Population</dt><dd>{item.population}</dd></div><div><dt>Map scope</dt><dd>{item.size}</dd></div></dl><div className="city-actions"><button onClick={() => open(item, false)}>Start fresh <span>→</span></button>{saved[item.id] && <button className="quiet" onClick={() => open(item, true)}>Continue</button>}</div></div></article>)}</section>{message && <p className="home-message" role="alert">{message}</p>}{replace && <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true"><h2>Replace saved plan?</h2><p>Starting a fresh {replace.name} plan removes the local save. This cannot be undone.</p><div><button className="quiet" onClick={() => setReplace(undefined)}>Cancel</button><button onClick={() => { deleteSession(replace.id); setSaved((current) => ({ ...current, [replace.id]: false })); setCity(replace); setReplace(undefined); }}>Start fresh</button></div></section></div>}</main>; }
