import { useMemo, useState } from 'react';
import type { Coordinate, World } from '../world';
import { ConstructionEngine, type ConstructionState } from './index';
import type { Economy } from '../economy';

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
export function ConstructionDebug({ world, coordinate, economy, onEconomyChange }: { readonly world: World; readonly coordinate: Coordinate | null; readonly economy: Economy; readonly onEconomyChange: () => void }) {
  const engine = useMemo(() => new ConstructionEngine(world), [world]); const [mode, setMode] = useState<'BUS' | 'TRAM' | 'SUBWAY'>('SUBWAY'); const [depth, setDepth] = useState(-24); const [start, setStart] = useState<Coordinate | null>(null); const [state, setState] = useState<ConstructionState>({ demolishedBuildingIds: [], engineeringSegments: [], stations: [] }); const [message, setMessage] = useState('Choose a mode, then use the last clicked map position to preview a proposal.');
  const commit = (result: ReturnType<ConstructionEngine['evaluate']>): boolean => { if (!result.plan) return false; if (!economy.recordConstruction(result.estimate, 0, result.plan.proposal.id)) { setMessage(`Unaffordable: ${currency.format(result.estimate.cost.total)} needed; cash is ${currency.format(economy.getCurrentCash() / 100)}. Take a loan in Finance.`); return false; } setState(engine.commit(result.plan, state)); onEconomyChange(); return true; };
  const previewStation = (): void => { if (!coordinate || mode !== 'SUBWAY') return setMessage('Select Subway and click a map position first.'); const result = engine.evaluate({ kind: 'station', id: `station-${state.stations.length + 1}`, mode: 'SUBWAY', elevationMeters: depth, footprint: { center: coordinate, widthMeters: 28, lengthMeters: 140 } }, state); if (result.valid && commit(result)) setMessage(`Committed station: ${currency.format(result.estimate.cost.total)}; ${result.estimate.demolitionImpacts.length} buildings affected.`); else if (!result.valid) setMessage(result.issues.map((issue) => issue.message).join(' ')); };
  const previewSegment = (): void => { if (!coordinate) return setMessage('Click a map position first.'); if (!start) { setStart(coordinate); return setMessage('Start set. Click another point, then evaluate the alignment.'); } const result = engine.evaluate({ kind: 'alignment', id: `segment-${state.engineeringSegments.length + 1}`, mode, geometry: [start, coordinate], verticalProfile: mode === 'SUBWAY' ? { startElevationMeters: depth, endElevationMeters: depth } : undefined }, state); if (result.valid && commit(result)) setMessage(`Committed ${mode.toLowerCase()} alignment: ${currency.format(result.estimate.cost.total)}${result.estimate.riverCrossingIds.length ? '; river engineering included.' : '.'}`); else if (!result.valid) setMessage(result.issues.map((issue) => issue.message).join(' ')); setStart(null); };
  return <section className="construction-debug"><p className="eyebrow">CONSTRUCTION DEBUG</p><h2>Engineering proposals</h2><label>Mode <select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="BUS">Bus</option><option value="TRAM">Tram</option><option value="SUBWAY">Subway</option></select></label>{mode === 'SUBWAY' && <label>Elevation (m) <input type="number" value={depth} max="0" onChange={(event) => setDepth(Number(event.target.value))} /></label>}<button type="button" onClick={previewStation}>Preview / commit station</button><button type="button" onClick={previewSegment}>Set start / evaluate alignment</button><p className="debug-note">{message}</p><dl><dt>Committed stations</dt><dd>{state.stations.length}</dd><dt>Committed alignments</dt><dd>{state.engineeringSegments.length}</dd><dt>Demolished buildings</dt><dd>{state.demolishedBuildingIds.length}</dd><dt>Depth convention</dt><dd>0m surface; negative underground</dd></dl></section>;
}
