import { useMemo, useState } from 'react';
import type { Coordinate, World } from '../world';
import { ConstructionEngine, type ConstructionState } from './index';
import type { Economy } from '../economy';

const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });
export function ConstructionDebug({ world, coordinate, economy, timestampSeconds, onEconomyChange, developerMode = false }: { readonly world: World; readonly coordinate: Coordinate | null; readonly economy: Economy; readonly timestampSeconds: number; readonly onEconomyChange: () => void; readonly developerMode?: boolean }) {
  const engine = useMemo(() => new ConstructionEngine(world), [world]); const [mode, setMode] = useState<'BUS' | 'TRAM' | 'SUBWAY'>('SUBWAY'); const [depth, setDepth] = useState(-24); const [start, setStart] = useState<Coordinate | null>(null); const [state, setState] = useState<ConstructionState>({ demolishedBuildingIds: [], engineeringSegments: [], stations: [] }); const [message, setMessage] = useState('Click the map to choose a location, then build a station or tunnel alignment.');
  const commit = (result: ReturnType<ConstructionEngine['evaluate']>): boolean => { if (!result.plan) return false; if (!economy.recordConstruction(result.estimate, timestampSeconds, result.plan.proposal.id)) { setMessage(`Unaffordable: ${currency.format(result.estimate.cost.total)} needed; cash is ${currency.format(economy.getCurrentCash() / 100)}. Take a loan in Finance.`); return false; } setState(engine.commit(result.plan, state)); onEconomyChange(); return true; };
  const previewStation = (): void => { if (!coordinate || mode !== 'SUBWAY') return setMessage('Select a map location first.'); const result = engine.evaluate({ kind: 'station', id: `station-${state.stations.length + 1}`, mode: 'SUBWAY', elevationMeters: depth, footprint: { center: coordinate, widthMeters: 28, lengthMeters: 140 } }, state); if (result.valid && commit(result)) setMessage(`Built station for ${currency.format(result.estimate.cost.total)}; ${result.estimate.demolitionImpacts.length} buildings affected.`); else if (!result.valid) setMessage(result.issues.map((issue) => issue.message).join(' ')); };
  const previewSegment = (): void => { if (!coordinate) return setMessage('Click a map location first.'); if (!start) { setStart(coordinate); return setMessage('Tunnel start set. Click an end point, then build the alignment.'); } const result = engine.evaluate({ kind: 'alignment', id: `segment-${state.engineeringSegments.length + 1}`, mode, geometry: [start, coordinate], verticalProfile: mode === 'SUBWAY' ? { startElevationMeters: depth, endElevationMeters: depth } : undefined }, state); if (result.valid && commit(result)) setMessage(`Built ${mode.toLowerCase()} alignment for ${currency.format(result.estimate.cost.total)}${result.estimate.riverCrossingIds.length ? '; river engineering included.' : '.'}`); else if (!result.valid) setMessage(result.issues.map((issue) => issue.message).join(' ')); setStart(null); };
  return <section className="construction-builder"><h3>Developer construction tools</h3><p className="builder-message">Raw engineering controls for debugging. Player construction uses the Subway and Tram tools.</p>{developerMode && <label>Override mode <select aria-label="Construction mode" value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="BUS">Bus</option><option value="TRAM">Tram</option><option value="SUBWAY">Subway</option></select></label>}<label>Elevation (0 surface; negative underground) <span className="input-with-unit"><input aria-label="Subway depth" type="number" value={depth} max="0" onChange={(event) => setDepth(Number(event.target.value))} /> m</span></label><div className="construction-actions"><button type="button" onClick={previewStation}>Build station here</button><button type="button" onClick={previewSegment}>{start ? 'Build tunnel to here' : 'Set tunnel start'}</button></div><p className="builder-message">{message}</p><div className="project-counts"><span><strong>{state.stations.length}</strong> stations built</span><span><strong>{state.engineeringSegments.length}</strong> alignments built</span></div>{developerMode && <section className="developer-construction-tools"><p className="eyebrow">DEVELOPER ENGINEERING</p><dl><dt>Demolished buildings</dt><dd>{state.demolishedBuildingIds.length}</dd><dt>Depth convention</dt><dd>0m surface; negative underground</dd><dt>Selected coordinate</dt><dd>{coordinate ? `${coordinate.latitude.toFixed(5)}, ${coordinate.longitude.toFixed(5)}` : 'None'}</dd></dl></section>}</section>;
}
