import { describe, expect, it } from 'vitest';
import { testCity } from '../levels/test-city';
import { World } from '../world';
import { ConstructionEngine } from './ConstructionEngine';

const point = (latitude: number, longitude: number) => ({ latitude, longitude });
const world = new World(testCity); const engine = new ConstructionEngine(world);
describe('Construction & Engineering System', () => {
  it('identifies building demolition but does not mutate source data before commit', () => { const proposal = { kind: 'station' as const, id: 'central', mode: 'SUBWAY' as const, elevationMeters: -20, footprint: { center: point(41.8698, -87.6404), widthMeters: 150, lengthMeters: 150 } }; const evaluation = engine.evaluate(proposal); expect(evaluation.valid).toBe(true); expect(evaluation.estimate.demolitionImpacts.length).toBeGreaterThan(0); expect(world.definition.buildings).toHaveLength(48); const state = engine.commit(evaluation.plan!); expect(state.demolishedBuildingIds).toEqual(evaluation.plan!.demolishedBuildingIds); expect(world.definition.buildings).toHaveLength(48); });
  it('makes deeper subway infrastructure cost more', () => { const shallow = engine.evaluate({ kind: 'station', id: 'shallow', mode: 'SUBWAY', elevationMeters: -10, footprint: { center: point(41.88, -87.62), widthMeters: 28, lengthMeters: 140 } }); const deep = engine.evaluate({ kind: 'station', id: 'deep', mode: 'SUBWAY', elevationMeters: -30, footprint: { center: point(41.88, -87.62), widthMeters: 28, lengthMeters: 140 } }); expect(deep.estimate.cost.total).toBeGreaterThan(shallow.estimate.cost.total); });
  it('rejects excessive grades and validates clear tunnel crossings', () => { const steep = engine.evaluate({ kind: 'alignment', id: 'steep', mode: 'SUBWAY', geometry: [point(41.87, -87.64), point(41.8701, -87.64)], verticalProfile: { startElevationMeters: -10, endElevationMeters: -30 } }); expect(steep.valid).toBe(false); expect(steep.issues[0].code).toBe('EXCESSIVE_GRADE'); const first = engine.evaluate({ kind: 'alignment', id: 'a', mode: 'SUBWAY', geometry: [point(41.871, -87.627), point(41.875, -87.623)], verticalProfile: { startElevationMeters: -14, endElevationMeters: -14 } }); const state = engine.commit(first.plan!); const collision = engine.evaluate({ kind: 'alignment', id: 'b', mode: 'SUBWAY', geometry: [point(41.873, -87.627), point(41.873, -87.621)], verticalProfile: { startElevationMeters: -17, endElevationMeters: -17 } }, state); expect(collision.issues.some((issue) => issue.code === 'INSUFFICIENT_TUNNEL_CLEARANCE')).toBe(true); const clear = engine.evaluate({ kind: 'alignment', id: 'c', mode: 'SUBWAY', geometry: [point(41.873, -87.627), point(41.873, -87.621)], verticalProfile: { startElevationMeters: -24, endElevationMeters: -24 } }, state); expect(clear.valid).toBe(true); });
  it('detects river crossings, requires depth, and costs tram versus bus correctly', () => { const crossing = { kind: 'alignment' as const, id: 'river', mode: 'SUBWAY' as const, geometry: [point(41.872, -87.633), point(41.872, -87.625)], verticalProfile: { startElevationMeters: -20, endElevationMeters: -20 } }; const invalid = engine.evaluate(crossing); expect(invalid.issues.some((issue) => issue.code === 'INSUFFICIENT_RIVER_DEPTH')).toBe(true); const valid = engine.evaluate({ ...crossing, verticalProfile: { startElevationMeters: -24, endElevationMeters: -24 } }); expect(valid.estimate.riverCrossingIds).toContain('junction-river'); expect(valid.estimate.cost.riverEngineering).toBeGreaterThan(0); const tram = engine.evaluate({ kind: 'alignment', id: 'tram', mode: 'TRAM', geometry: [point(41.87, -87.64), point(41.871, -87.64)] }); const bus = engine.evaluate({ kind: 'alignment', id: 'bus', mode: 'BUS', geometry: testCity.roads[0].geometry }); expect(tram.estimate.cost.total).toBeGreaterThan(0); expect(bus.valid).toBe(true); expect(bus.estimate.cost.total).toBe(0); });
});
