import { describe, expect, it } from 'vitest';
import { createLine, createStop, makeLine, TransitNetwork } from '../transit';
import { modeRegistry } from '../modes';
import { OperationsSimulation } from './OperationsSimulation';
const point = (latitude: number, longitude: number) => ({ latitude, longitude });
const network = (): TransitNetwork => { let value = new TransitNetwork(); value = createStop(value, { id: 'a', name: 'A', coordinate: point(41.88, -87.63), kind: 'stop', supportedModes: ['BUS'] }); value = createStop(value, { id: 'b', name: 'B', coordinate: point(41.88, -87.629), kind: 'stop', supportedModes: ['BUS'] }); return createLine(value, makeLine('bus', 'Bus', 'BUS', ['a', 'b'], value)); };
const config = (count = 1, active = true) => ({ lineId: 'bus', active, vehicleTypeId: 'standard-bus', assignedVehicleCount: count, frequency: { daytimeHeadwayMinutes: 4, nighttimeHeadwayMinutes: 20, daytimeStartHour: 0, nighttimeStartHour: 23 } });
describe('Vehicles & Operations', () => {
  it('dispatches deterministically, moves by simulation time, and emits operating costs', () => { const operations = new OperationsSimulation(network(), [config()]); operations.advance(60); const vehicle = operations.snapshot().vehicles[0]; expect(vehicle).toBeDefined(); expect(operations.drainEvents().some((event) => event.type === 'VEHICLE_OPERATING_COST')).toBe(true); operations.advance(60); expect(operations.snapshot().vehicles[0].coordinate.longitude).toBeGreaterThanOrEqual(vehicle.coordinate.longitude); });
  it('boards, applies capacity, alights, and emits a fare event', () => { const operations = new OperationsSimulation(network(), [config()]); for (let index = 0; index < 75; index += 1) operations.enqueuePassenger(`p-${index}`, 'a', 'b'); operations.advance(1); const snapshot = operations.snapshot(); expect(snapshot.statistics.boardings).toBe(70); expect(snapshot.statistics.deniedBoardings).toBeGreaterThan(0); expect(operations.drainEvents().filter((event) => event.type === 'FARE_CHARGED')).toHaveLength(70); operations.advance(300); expect(operations.snapshot().statistics.alightings).toBe(70); });
  it('keeps unserved demand visible and respects deactivation/vehicle availability', () => { const inactive = new OperationsSimulation(network(), [config(1, false)]); expect(inactive.enqueuePassenger('missing', 'b', 'a')).toBe(false); inactive.advance(600); expect(inactive.snapshot().vehicles).toHaveLength(0); const unavailable = new OperationsSimulation(network(), [config(0)]); unavailable.advance(300); expect(unavailable.snapshot().warnings[0]).toMatch(/insufficient/); });
  it('uses mode capacity and rejects incompatible vehicle choices', () => { expect(modeRegistry.getVehicleDefinition('standard-bus').capacity).toBe(70); expect(() => new OperationsSimulation(network(), [{ ...config(), vehicleTypeId: 'standard-tram' }])).toThrow(/not compatible/); });
});
