import { distanceMeters, interpolatePolyline } from '../map';
import { modeRegistry, validateServiceFrequency } from '../modes';
import { TransitNetwork } from '../transit';
import type { TransitLine } from '../transit';
import type { LineServiceConfiguration, OperationsEvent, OperationsSnapshot, OperationsStatistics, VehicleRuntime, WaitingPassenger } from './types';

const emptyStats = (): OperationsStatistics => ({ boardings: 0, alightings: 0, deniedBoardings: 0, unservedDemand: 0, totalWaitSeconds: 0, maximumWaitSeconds: 0, operatingVehicleSeconds: 0, byLine: {} });
const lineLength = (line: TransitLine): number => line.segments.reduce((total, segment) => total + segment.geometry.slice(1).reduce((sum, point, index) => sum + distanceMeters(segment.geometry[index], point), 0), 0);
/** Deterministic service simulator advanced solely by explicit simulation seconds. */
export class OperationsSimulation {
  private timeSeconds = 0; private vehicles: VehicleRuntime[] = []; private readonly queues = new Map<string, WaitingPassenger[]>(); private readonly lastDispatch = new Map<string, number>(); private readonly configurations = new Map<string, LineServiceConfiguration>(); private stats = emptyStats(); private events: OperationsEvent[] = []; private warnings: string[] = [];
  public constructor(private readonly network: TransitNetwork, configurations: readonly LineServiceConfiguration[]) { configurations.forEach((configuration) => this.configureLine(configuration)); }
  public configureLine(configuration: LineServiceConfiguration): void { const line = this.network.getLine(configuration.lineId); if (!line) throw new Error(`Unknown line "${configuration.lineId}"`); const vehicle = modeRegistry.getVehicleDefinition(configuration.vehicleTypeId); if (vehicle.modeId !== line.mode) throw new Error(`Vehicle "${vehicle.id}" is not compatible with line "${line.id}"`); validateServiceFrequency(configuration.frequency, modeRegistry.getModeDefinition(line.mode).operations.minimumHeadwayMinutes); if (!Number.isInteger(configuration.assignedVehicleCount) || configuration.assignedVehicleCount < 0) throw new Error('Assigned vehicle count must be a nonnegative integer.'); this.configurations.set(line.id, configuration); }
  public enqueuePassenger(id: string, originStopId: string, destinationStopId: string): boolean { const direct = this.network.definition.lines.find((line) => line.active && line.stopIds.indexOf(originStopId) >= 0 && line.stopIds.indexOf(destinationStopId) > line.stopIds.indexOf(originStopId)); if (!direct) { this.stats = { ...this.stats, unservedDemand: this.stats.unservedDemand + 1 }; return false; } const queue = this.queues.get(originStopId) ?? []; this.queues.set(originStopId, [...queue, { id, destinationStopId, arrivedAtSeconds: this.timeSeconds, farePaid: false }]); return true; }
  public advance(deltaSeconds: number): void { if (!Number.isFinite(deltaSeconds) || deltaSeconds < 0) throw new Error('Operations advancement requires nonnegative simulation seconds.'); const target = this.timeSeconds + deltaSeconds; while (this.timeSeconds < target) { const step = Math.min(1, target - this.timeSeconds); this.dispatch(); this.moveVehicles(step); this.chargeOperatingCosts(step); this.timeSeconds += step; } }
  private dispatch(): void { const hour = Math.floor((this.timeSeconds / 3600) % 24); for (const line of this.network.definition.lines) { const config = this.configurations.get(line.id); if (!config?.active || !line.active) continue; const headwayMinutes = hour >= config.frequency.daytimeStartHour && hour < config.frequency.nighttimeStartHour ? config.frequency.daytimeHeadwayMinutes : config.frequency.nighttimeHeadwayMinutes; const activeCount = this.vehicles.filter((vehicle) => vehicle.lineId === line.id).length; const last = this.lastDispatch.get(line.id) ?? -Infinity; if (activeCount < config.assignedVehicleCount && this.timeSeconds - last >= headwayMinutes * 60) { const start = this.network.getStop(line.stopIds[0])!; const id = `${line.id}-vehicle-${activeCount + 1}-${Math.floor(this.timeSeconds)}`; const vehicle: VehicleRuntime = { id, lineId: line.id, vehicleTypeId: config.vehicleTypeId, state: 'DWELLING', stopIndex: 0, segmentProgressMeters: 0, dwellRemainingSeconds: 0, passengers: [], coordinate: start.coordinate }; this.vehicles = [...this.vehicles, this.serviceStop(vehicle)]; this.lastDispatch.set(line.id, this.timeSeconds); } else if (activeCount >= config.assignedVehicleCount && this.timeSeconds - last >= headwayMinutes * 60) { const warning = `Line ${line.id} has insufficient assigned vehicles for its requested headway.`; if (!this.warnings.includes(warning)) this.warnings = [...this.warnings, warning]; } } }
  private moveVehicles(step: number): void { this.vehicles = this.vehicles.map((vehicle) => { const line = this.network.getLine(vehicle.lineId)!; const template = modeRegistry.getVehicleDefinition(vehicle.vehicleTypeId); if (vehicle.state === 'DWELLING') { const remaining = vehicle.dwellRemainingSeconds - step; return remaining > 0 ? { ...vehicle, dwellRemainingSeconds: remaining } : { ...vehicle, state: 'TRAVELING', dwellRemainingSeconds: 0 }; } const segment = line.segments[vehicle.stopIndex]; if (!segment) return vehicle; const length = lineLength({ ...line, segments: [segment] }); const progressed = vehicle.segmentProgressMeters + template.maximumSpeedKph * 1000 / 3600 * step; if (progressed < length) return { ...vehicle, segmentProgressMeters: progressed, coordinate: interpolatePolyline(segment.geometry, progressed) }; const nextIndex = vehicle.stopIndex + 1; const arrived = { ...vehicle, stopIndex: nextIndex, segmentProgressMeters: 0, coordinate: this.network.getStop(line.stopIds[nextIndex])!.coordinate }; return this.serviceStop(arrived); }); }
  private serviceStop(vehicle: VehicleRuntime): VehicleRuntime { const line = this.network.getLine(vehicle.lineId)!; const template = modeRegistry.getVehicleDefinition(vehicle.vehicleTypeId); const stopId = line.stopIds[vehicle.stopIndex]; const alighting = vehicle.passengers.filter((passenger) => passenger.destinationStopId === stopId); const continuing = vehicle.passengers.filter((passenger) => passenger.destinationStopId !== stopId); const queue = this.queues.get(stopId) ?? []; const available = template.capacity - continuing.length; const boarding = queue.slice(0, Math.max(0, available)); const left = queue.slice(boarding.length); this.queues.set(stopId, left); if (left.length > 0) this.stats = { ...this.stats, deniedBoardings: this.stats.deniedBoardings + left.length }; for (const passenger of boarding) { const wait = this.timeSeconds - passenger.arrivedAtSeconds; this.stats = { ...this.stats, boardings: this.stats.boardings + 1, totalWaitSeconds: this.stats.totalWaitSeconds + wait, maximumWaitSeconds: Math.max(this.stats.maximumWaitSeconds, wait), byLine: { ...this.stats.byLine, [line.id]: { boardings: (this.stats.byLine[line.id]?.boardings ?? 0) + 1, alightings: this.stats.byLine[line.id]?.alightings ?? 0 } } }; if (!passenger.farePaid) this.events.push({ type: 'FARE_CHARGED', lineId: line.id, vehicleId: vehicle.id, passengerId: passenger.id, amountCents: modeRegistry.getModeDefinition(line.mode).operations.defaultFare.fareCents, timestampSeconds: this.timeSeconds }); }
    if (alighting.length) this.stats = { ...this.stats, alightings: this.stats.alightings + alighting.length, byLine: { ...this.stats.byLine, [line.id]: { boardings: this.stats.byLine[line.id]?.boardings ?? 0, alightings: (this.stats.byLine[line.id]?.alightings ?? 0) + alighting.length } } };
    const dwell = (modeRegistry.getModeDefinition(line.mode).operations.defaultDwellSeconds + boarding.length + alighting.length) * template.dwellTimeModifier; return { ...vehicle, state: 'DWELLING', dwellRemainingSeconds: dwell, passengers: [...continuing, ...boarding.map((passenger) => ({ ...passenger, farePaid: true }))] }; }
  private chargeOperatingCosts(step: number): void { this.vehicles.forEach((vehicle) => { const cost = modeRegistry.getVehicleDefinition(vehicle.vehicleTypeId).operatingCostPerHour * 100 * step / 3600; this.events.push({ type: 'VEHICLE_OPERATING_COST', lineId: vehicle.lineId, vehicleId: vehicle.id, amountCents: Math.round(cost), timestampSeconds: this.timeSeconds }); }); this.stats = { ...this.stats, operatingVehicleSeconds: this.stats.operatingVehicleSeconds + this.vehicles.length * step }; }
  public drainEvents(): readonly OperationsEvent[] { const events = this.events; this.events = []; return events; }
  public snapshot(): OperationsSnapshot { return { simulationSeconds: this.timeSeconds, vehicles: this.vehicles, queues: Object.fromEntries(this.queues), statistics: this.stats, warnings: this.warnings }; }
}
